### PR TITLE
Added MLDonkey Rock-On with edonkey, kademlia, overnet and bittorrent…

### PR DESCRIPTION
**Pull request by AngeleToR**
Well.... my first commit in github to a project not mine, not sure what to do now... Any suggestion for improving my rockon will be welcomed.

Tested and already running in my system with latest Rockstor 3.8-13.15, changing ports or mldonkey user uid/gid from the ones I use can be tricky and will make the rock-on fail if there's no command line tinkering, so just DON'T do it until I learn how to fix it.

Any suggestion, advice, improvement... will be more than welcome...

### CODE REVIEW

**Comment by schakrava** [comment]
Hi @AngeleToR Thanks for your interest in contributing to Rockstor. I'd be happy to review and accept your contribution. I have a question to begin with. Do we really need host networking(--net=host)? Have you tested without it?

**Comment by AngeleToR** [comment]
Hi @schakrava Honestly, I haven't tried it in bridged mode. Every docker I've seen for MLDonkey, including the one my rockon is based on, uses hot networking. I suppose it is because of the massive amount of ports it will open while running.... By the way, for the time being it is important to use the default ports provided, there are some issues if they're changed right now. I only show them in the interface so users know which ones to open in their routers.
SO, back to your question, could it run in bridged mode?? Maybe, though I haven't tested it and would require modifying the docker and right now I'm out of time to test it, sorry....
Anyway if you or other user wants to give it a try and modify/improve my work, you're more than welcome, that's what free software is all about ;-)

**Comment by phillxnet** [comment]
@AngeleToR Thanks again for you effort on this one.

I'm going to label as help wanted for the time being as I need another opinion on which way to go with this. We are trying to avoid "--net=host" where we can and this docker image is now 2 years old so unless anyone else wishes pickup this one where @AngeleToR left off I think we will put this pr on notice of closure soon.

More input, as always, is welcome.

**Comment by phillxnet** [comment]
@AngeleToR Apologies for no follow up on this for a few months. Unfortunately as the docker image used has now not received any attention in 3 years (But was current at the time of your pull request!) and the use of --net=host on such a program, I'm inclined to close this pr.

Apologies again for the negligence on our part. Do please open a fresh Rock-on pull request if you end up finding a more maintained docker image. I'm in the throws of doing a long needed tidy in this repository in the hope that it will ultimately be easier to manage for our volunteer reviewers.

We have not done what was stated as your first GitHub pull request any justice I'm afraid.
And thanks again for at least attempting to contribute to Rockstor's Rock-ons. We do now have a little more help on the Rock-on maintenance front so hopefully we can do more justice to contributors efforts in the future. If you do fancy revisiting this specific Rock-on then do please re-open and add the appropriate update commits to this same branch and we can take it from there.

**Pull request closed without merging**
