### PR TITLE
Proposal to add Lyrion Media Server (successor of Logitech Media Server)

### PR DESCRIPTION
**Pull request by alexjulien**
Fixes # .

### General information on project
This pull request proposes to add a new rockon for the following project:
- name: Lyrion Music Server
- website: https://lyrion.org/
- description: Rockstor already has a Logitech Media Server (lms) rockon. But LMS is being rebranded/superseded by Lyrion Music Server (now, officially away from Logitech, thanks for all the years of support!). So, the latest LMS container is not getting updated anymore. This is a first attempt to include Lyrion on Rockstor.

### Information on docker image
- docker image: https://registry.hub.docker.com/r/lmscommunity/lyrionmusicserver
- is an official docker image available for this project?: Yes. But for some reason, at the time of writing, the ` latest` tag cannot be pulled. That is why this rockon pulls ` dev`.

### Checklist
- [X] Passes [JSONlint](https://jsonlint.com) validation
- [X] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [X] `"description"` object lists and links to the docker image used
- [X] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [X] `"website"` object links to project's main website

### CODE REVIEW

**Comment by phillxnet** [comment]
@alexjulien Hello there, and thanks for this submission.

Have seen the proposed change here by @Hooverdan96 ?

Replace LMS docker image with new community version (#381) #382

**Comment by phillxnet** [comment]
OK, so I've now just merged and published @Hooverdan96 prior counterpart to this Rock-on. Again apologies all around for the delays in getting this done.

@Hooverdan96 & @alexjulien is this PR now redundant?

@alexjulien if you now click the `Update button` in your Rock-ons page, there should be @Hooverdan96's Rock-on available for:

- [Lyrion Media Server - Latest Stable](https://lyrion.org/)

If your own is still in a local file repository it may interfere. Just remove you local instance to resolve this: if it does in fact clash in some way.

**Comment by alexjulien** [comment]
I agree: my PR is definitely redundant. Specially since I haven't tested in
depth. I've been using it for the last couple of days with no issues, but
that's about it.

**Comment by phillxnet** [comment]
Closing as functional duplicate of now merged #382. Thanks again @alexjulien for this effort, much appreciated.

Duplicate of #382

**Pull request closed without merging**
