### PR TITLE
Adding in minio.io storage provider.

### PR DESCRIPTION
**Pull request by jmhardison**
Minio.io is a distributed object storage server providing S3 compatibility.
I was not able to find where I can enter a launch command for docker run outside of what I saw in the core code that had custom extends for specific images. So I've created a custom docker image that sources from minio/minio and changes the launch to server mode. (Build hooks set to minio/minio so it will always remain up to date with core.)

This container will expose 9000/tcp and use several environment variables to turn on the portal and set user/pass. (The user and password get generated automatically if not defined, which would be in the console log of the container and not exposed.)

Check http://minio.io for more info.

Testing simply can be performed by enabling the web ui, and then interacting with the portal. Otherwise you can follow examples for console or code from minio.io.

### CODE REVIEW

**Comment by magicalyak** [comment]
Any reason the base docker minio couldn't be used?  We try to stay away from any docker hub custom builds when we can, generally look for project owner, linuxserver.io first if possible.

**Comment by jmhardison** [comment]
If I remember right it was because the base image does not have defaults for the mode (server) and export path, and from what I could tell a rockon didn't have the ability to do command and arguments that follow a docker run command. (currently) Be happy to revert to the root for that, but those fields are required to launch correctly. Unless I completely missed where/how that can be done in a rockon. I saw of course the ability to do options such as environment, but not command arguments.

Linuxserver.io also does not have a drop for this. I could approach minio and see if they are willing to implement defaults when no mode or argument is provided to the executing container to default it to server mode with a path. (Effectively mirror their example command into the default state given a run with no args.)

Feel free to sits as I chase that, if they accept I can either report back or update the request back to root image once merged.

**Comment by jmhardison** [comment]
Well that's a more direct no.
https://github.com/minio/minio/pull/3030

> We had to make this breaking change since minio has other sub-commands, it was our mistake that "server" was included as part of the entrypoint earlier.
To run docker properly now the right command is
docker run -p 9000:9000 minio/minio server /export

and

> harshavardhana commented on Oct 21 2016 
Thanks for the patch @olalonde - but we are not going to default any commands for docker container . Docs become inconsistent with regular binary releases

I'll go submit a request to linuxserver.io and see if they want to pull it into themselves. End of the day, either that or if there is a way to make rockons use custom args in a launch command.

**Comment by magicalyak** [comment]
I think that's adequate explanation. I'll review soon using your container.

**Comment by jmhardison** [comment]
As work is being completed to add argument support, I'm going to close out this pull request.

**Comment by FroggyFlox** [comment]
Glad the argument support could be of some help to you, @jmhardison. Please let me know if it is still lacking in any way.

**Pull request closed without merging**
