### PR TITLE
Remove all non-functional or outdated Rock-ons #335

### LINKED ISSUE #313: owncloud-official.json and owncloudHTTPS.json should be updated/deprecated
the official https://hub.docker.com/_/owncloud image used in both those Rockons has a deprecation notice on the web page (not been updated since December 2018), referring users to the https://hub.docker.com/r/owncloud/server/ image.

Probably deprecate those two and create a new one using the new official image by owncloud itself

### LINKED ISSUE #314: Rockon Postgres Versions stale?
The underlying images for the two dedicated Postgres Rockons have not been updated/pushed in quite some time:
postgres-10.6.json last update over 3 years ago
postgres-9.5.json last updated over 2 years ago

Does this pose a security risk, etc.? Should we replace these with a much more recent version? Comes back to another conversation on surfacing the tags in the Rockon configuration, so we don't have to manage version-specific Rockons for things like DBMS as they are bound to change over time.

### LINKED ISSUE #316: subsonic Rockon container last update 5 yrs ago
subsonic.json - the underlying container was last updated 5 years ago. This image could possibly replaced with the one found here https://hub.docker.com/r/hydria/subsonic/ that seems more active.

### LINKED ISSUE #318: Xeoma image stale?
The images user for xeoma.json was last updated 2 years ago. Is there one that could be used in its place that's more active?

### LINKED ISSUE #319: zoneminder-latest image deprecated?
The image underlying the zoneminder-latest.json https://hub.docker.com/r/dlandon/zoneminder has a deprecation notice on it. Is there a newer image that could be carried forward or keep this one in place (since the image is still there) for some more time while figuring out what to do.

### LINKED ISSUE #326: Rocket.chat Rockon non-functional
Based on @wwwizzarrdry's comment I took a stab at getting the rocket.chat Rockon to run. Same negative outcome unfortunately. When reviewing the logs it seems that the current Rockon is missing some settings (related to Mongo DB) that are now required in the newer versions of rocket.chat. 
When I reviewed the installation information on their website, it seems it now relies on some Mongo DB replication service (or something to that effect) that requires an additional container to be run once separately ([mongo replica container](https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose/docker-containers/systemd#build-the-mongo-init-replica-container-only-run-once))
So, I suspect the Rockon needs to be revamped and some install docs need to be created (or maybe the rocket.chat solution docks are sufficient as reference).

### PR DESCRIPTION
**Pull request by phillxnet**
Removes all Rock-ons associated with GitHub issues:
- Drop deprecated Subsonic Rock-On ... #307 (recent activity here).
- Subsonic Rockon container last update 5 yrs ago #316 (related to above)
- owncloud-official.json and owncloudHTTPS.json should be updated/deprecated #313
- Rockon Postgres Versions stale? #314
- Xeoma image stale? #318
- zoneminder-latest image deprecated? #319
- Rocket.chat Rockon non-functional #326

Partly addresses #307
Fixes #316 (already closed as duplicate of above but referencing here for info purposes)
Fixes #313
Fixes #314
Fixes #318
Fixes #319
Fixes #326
Ready for review.

## Also includes:
- Remove orphaned home-assistant.json (missing root.json entry).
- "Watchtower offical" which should read: "Watchtower official"

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation (in this case the pr product on root.json)

### CODE REVIEW

**Comment by phillxnet** [comment]
In keeping with the proposed approach embodied by this pr and detailed in the associated issue I've now tested this pr on a local repo from a system that previously used the production repo and all intended deletes look to have taken effect, with a no-errors update there after.

Merging to clear the way for our more recent activity on new Rock-ons in this repo.

If you have pending fixes for any of these removed Rock-ons then do please open a new pull request based on current master post this pr's merge as we can then re-test /review re-add as needed without leaving dead Rock-ons in production in the mean time. Better all around hopefully.

**Comment by phillxnet** [comment]
@FroggyFlox & @Hooverdan96 my apologies for merging this without review. Just trying to do a little towards getting out Rock-ons repo a little lighter on the backlog and remove any pressure to fix broken stuff that has thus received insufficient attention so we can clear the way for more currently active pull requests and make the entire repo a little more approachable, hopefully.

In the future I propose we move to delete fast any non functional Rock-ons, thus freeing resources and reducing frustration all around. A fix is always better, if presented and reviewed in a timely manner, but far harder to come by. And no deletion precludes a later fix and re-add.

**Comment by phillxnet** [comment]
PR product production published.

**Comment by Hooverdan96** [comment]
@phillxnet  thanks for driving this to closure. I trust that your test would have revealed any issues before the merge. No concern from my side.

**Pull request merged**
