### PR TITLE
Cops

### PR DESCRIPTION
**Pull request by sparklyballs**
PR for consideration, adding [cops](http://blog.slucas.fr/en/oss/calibre-opds-php-server) as a rockon

### CODE REVIEW

**Comment by schakrava** [comment]
Thanks @sparklyballs Is this ready to be reviewed and merged?

**Comment by sparklyballs** [comment]
@schakrava , yes
if you could review and let me know if anything missing, and that it ok.

**Comment by schakrava** [comment]
I had to fixup the file a bit, but looks good over all. Thank you @sparklyballs 

The rock-on installed fine, but when I access the UI there is Database Error.

cops_db_error

**Comment by CHBMB** [comment]
@schakrava Have you pointed /books to the location where a calibre database is?  If not, then this error would be expected.

https://github.com/linuxserver/docker-cops#parameters

**Pull request merged**
