### PR TITLE
Add gollum rock-on

### PR DESCRIPTION
**Pull request by guppy0130**
Working on my local installation v3.9.1-0

## Image source
https://hub.docker.com/r/adtac/gollum-alpine/

## Ports
| Container | Device |
|------------|---------|
| 8080        | 8082     |

## Volumes
Container: /wiki

### CODE REVIEW

**Comment by phillxnet** [comment]
@guppy0130 Thanks for the contribution, most welcome.

As a relevant aside, could you also test on a more up to date Rockstor. I.e subscribe to one or other update channels and you should then get quite a few more fixed as 3.9.1-0 is now quite old. Shouldn't make a difference but just in case. Also make sure to confirm you resulting installed version via:
```
yum info rockstor
```
Thanks and well done on taking the effort re the branch for the pull request.

**Comment by magicalyak** [comment]
@schakrava this is ready to merge

**Comment by phillxnet** [comment]
@guppy0130 Thanks again for another Rock-on submission/fix and re-testing this one on a newer Rockstor instance. And again apologies this merge took so long.

@magicalyak Thanks for another in a long line of reviews. Much appreciated.

**Comment by phillxnet** [comment]
Adding link to issue to update our root.json for this pull request:
"missing root.json entries" #171

**Pull request merged**
