### PR TITLE
Add Xeoma Video Surveillance Rockon

### PR DESCRIPTION
**Pull request by mattwire**

### CODE REVIEW

**Comment by magicalyak** [comment]
Does the ui work?  Can you add "ui": true to the port option or remove the ui slug section if not?

**Comment by mattwire** [comment]
@magicalyak I've removed the ui section.

**Comment by magicalyak** [comment]
Looks good to me! @schakrava just needs to merge

**Comment by schakrava** [comment]
Thank you @mattwire and @magicalyak

**Pull request merged**
