### PR TITLE
Crashplan rockon

### PR DESCRIPTION
**Pull request by badriram**
Created a rockon for crashplan that works headless. It requires some active copying of credentials to a desktop with UI to make use of it. 
https://support.crashplan.com/Configuring/Using_CrashPlan_On_A_Headless_Computer

### CODE REVIEW

**Comment by magicalyak** [comment]
Since there is no ui, can you disable the slug section?  Otherwise this looks good and is from a well-used docker repo (250k pulls).

**Comment by badriram** [comment]
Updated. thanks, was unsure if that section was required.

**Comment by magicalyak** [comment]
Ok something's broken with the more_info section though.  It's the <a href section.  I'd take out the HTML markup and eliminate the " symbols.  It's basically closing the more_info on the JSON with the " right before https:// 
hope that makes sense.
So instead of
`<a href="https://support.crashplan.com/Configuring/Using_CrashPlan_On_A_Headless_Computer">Crashplan: Using crashplan Headless</a></p>",`
do
`https://support.crashplan.com/Configuring/Using_CrashPlan_On_A_Headless_Computer</a></p>",`
and it should work.

**Comment by magicalyak** [comment]
Also don't need the TZ, just remove it.  However we already have a #79 pending so if that person modifies first, they might be merged instead (just a heads up).

**Comment by magicalyak** [comment]
Oh otherwise great work, should have mentioned that.

**Comment by badriram** [comment]
should be all set.

**Comment by magicalyak** [comment]
Gotta wait for @schakrava to approve the merge but it looks good, thanks for working on it.

**Comment by schakrava** [comment]
Thanks @badriram for your contribution and Thank you @magicalyak for your review!

**Pull request merged**
