### PR TITLE
Remove-Sickbeard-RockOn-(unmaintained) #241 (#2)

### LINKED ISSUE #249: Remove deprecated Sickrage image
Follow-on to #240 .
Now that SickRage has been replaced by its successor SickChill as a Rock-on we can deprecate the SickRage Rock-On

### PR DESCRIPTION
**Pull request by Hooverdan96**
Fixes #249 .

General information on project
Since SickRage has been superseeded by SickChill and a corresponding Rock-on has been created, the SickRage Rock-on can be removed from the repository

modified: root.json (remove SickRage entry)
deleted: sickrage.json

### CODE REVIEW

**Comment by Hooverdan96** [comment]
@FroggyFlox - let's see whether this works. Sorry for making you also teach me the ins and outs of git. I do appreciate very much, though!

**Comment by FroggyFlox** [comment]
> Sorry for making you also teach me the ins and outs of git.

No worries, we're always to share whatever we can/know.

Unfortunately, I'm afraid this one is problematic as well: if you look at the bottom of this page, you will see that Github states "This branch has conflicts that must be resolved". Unless very specific cases, this should not happen and does signify issues with the branch used for the PR. I can see a few issues myself here:

1. You seem to have used your `master` branch. This is generally not recommended as it leads to more problems than anything else. The recommended way is to create a dedicated branch for the issue you aim to fix that is then used only for that. 
2. Your branch doesn't seem to have been rebased (on at least not on the latest upstream) before you committed your changes. I can see this in due to the following: you are proposing to deprecate the Sickbeard rock-on, which has already been deprecated as of #243. As `sickbeard.json` has already been removed by #243, this file should not still be present in your `master` branch after its rebase on latest upstream.
3. The rock-on that still needs to be removed is SickRage (`sickrage.json`) as per #249, not Sickbeard.

If you follow the steps described in the README, it should all be ok. Make sure to verify all three points before confirming the PR submission and it should be fine.
https://github.com/rockstor/rockon-registry#steps-to-contribute-a-rock-on-with-a-pull-request

Don't hesitate to DM me on the forum in case you have more questions and hopefully I'll be able to help further there if needed.

**Comment by Hooverdan96** [comment]
Thanks @FroggyFlox, really appreciate your patience here. 
Let's do this. I will close the pull request, wait for you to merge the watchtower deprecation pull request, and then will rebase everything on my side and start over.
I used the pushed commit from my local repository (using a branch and not the master) to open a new pull request but it was based on the "old" one and I didn't go through all of the steps again, it somehow ended up as a master branch pull request ... what a mess.

**Comment by FroggyFlox** [comment]
> Let's do this. I will close the pull request, wait for you to merge the watchtower deprecation pull request, and then will rebase everything on my side and start over.

@Hooverdan96 , #250 has now been merged so you can go ahead on your side.

Cheers,

**Pull request closed without merging**
