### PR TITLE
added dns options for pi-hole rockon

### PR DESCRIPTION
**Pull request by magicalyak**
Updated from https://github.com/rockstor/rockon-registry/pull/156
Issue - https://github.com/rockstor/rockon-registry/issues/176

This is a continuation of the previous PR and adds the dns needed by @haioken
This still needs a test which I hope to do shortly but could use feedback on if others want to test.
I may also clean up the rockon a bit (DNS1 and 2 may be unnecessary and I need to verify TZ).

### CODE REVIEW

**Comment by magicalyak** [comment]
added https://github.com/haioken request dnsmasq vol that @FroggyFlox mentioned
changed to official image
cleaned up options
specified no to IPv6 (you needed a lot more options to make it true anyway).

**Comment by phillxnet** [comment]
@magicalyak This look good, thanks for getting this one moving again. Quite looking forward to merging this.

I've go one minor quick request though. We are trying to move towards the website element linking to the upstream project, ie in this case Pi-hole itself ie:
https://pi-hole.net/

and for the time being, at least until we do this programmatically or via an additional docker_hub_url json element or the like, we are embedding in the description via html a link to the docker hub image.

Please see @FroggyFlox recent Teamspeak3 json in repo for an example of this. It also 'fakes' via paragraph formatting a 'subtitle' containing this link. That way less technical users can link to sight from the Title (website json element) and we also present the info available via the (docker hub) link within the description.

That would be dandy. Just trying to move towards all new submissions containing both links:
See issue #178 on this.

**Comment by magicalyak** [comment]
Description changed

**Comment by magicalyak** [comment]
lol had a typo - I am testing this now.

**Comment by magicalyak** [comment]
After fixing typo and index - Tests PASSED for me

**Comment by phillxnet** [comment]
@magicalyak Thanks for the description change. That's much better.

pi-hole-rock-on

But the title still links to the docker hub page. Could we possibly have this updated to the Pi-Hole's own project. That way we surface their main page complete with their donate options and the like. I.e. this looks good to me bar the "website": update to https://pi-hole.net.

Bar that, given @haioken and @FroggyFlox have had a hand in this pr's direction (see @laxdog's original work on the image change in the now deprecated pr #156), I'd like a quick review from either of them on the more functional side. I haven't used Pi-Hole before but these pull requests have peaked my interest.

**Comment by phillxnet** [comment]
@magicalyak Thanks for the website element fix, much nicer.
Both links now work as intended.

We just need a quick review from @haioken or @FroggyFlox to make sure they are happy and I'll pop this in.

Well done persevering with this one. Will be great to have it done and dusted.

**Comment by magicalyak** [comment]
@FroggyFlox that works for me, did you want to submit the commit or should we go as is?

**Comment by magicalyak** [comment]
Removed the options, this should be good to go @phillxnet

**Comment by phillxnet** [comment]
@magicalyak Thanks for rounding this one out, hopefully finally.
@FroggyFlox Your final thoughts on this one if you would. Are you happy with me merging as is, as per you last review here?

Thanks people, itching to get this one in so lets pull it to a close.

**Comment by FroggyFlox** [comment]
Thanks again @magicalyak for your orignal PR and all the edits! 

@phillxnet, the commits since my Github review look good to me, and after a quick test on Rockstor-3.9.1-16, it installs OK, starts OK, and the webUI is accessible without error through Rockstor's webUI button.

**Comment by phillxnet** [comment]
Thanks to @magicalyak for pulling this one together and to @laxdog (original pr #156) @FroggyFlox for multiple reviews / suggestions, @haioken for advise / input.

Fixes #176

**Pull request merged**
