### PR TITLE
Deprecate legacy Watchtower Rock-on (Fixes #248)

### LINKED ISSUE #248: Deprecate old Watchtower Rock-on
Continuation of issue #233 
Since we now introduced the Watchtower Rock-on based on the official container, we can deprecate the legacy version we had so far, which uses a docker image that appears to be unmaintained.

### PR DESCRIPTION
**Pull request by Hooverdan96**
Fixes #248 .

### General information on project
remove Rock-on based on unofficial image, since we now have the watchtower Rock-on based on the official image (see Pull Request #247 ).
modified: root.json - remove legacy Watchtower entry
deleted: watchtower.json

### CODE REVIEW

**Comment by Hooverdan96** [comment]
@FroggyFlox - here's the legacy watchtower removal request. Once that's merged, I will take care of the removal of the SickRage Rock-On.

**Comment by FroggyFlox** [comment]
Thanks a lot!

I'll have a look at it shortly.

Note that you don't need to wait for this one to be merged before submitting the other PR as they probably won't interfere with each other.

**Comment by Hooverdan96** [comment]
with my limited experience I am not sure about the "overlap" in the root.json file ... I'll check it out.

**Review by FroggyFlox — APPROVED** [review]

**Comment by FroggyFlox** [comment]
@Hooverdan96 , thanks for this PR. All looks good so I'm merging it now.

**Pull request merged**
