### PR TITLE
Added NZBHydra

### PR DESCRIPTION
**Pull request by porkie02**

### CODE REVIEW

**Comment by porkie02** [comment]
hopefully this is correct now.

**Comment by phillxnet** [comment]
@porkie02 Thanks for getting this sorted and the other 2 also (fast work there).
Yes now in it's own branch and with a less generic name. Sorted.

The tab characters issue is still outstanding if you fancy adding another commit on this branch to sort that and in turn on the other prs / branches if need be.

Cheers.

**Comment by securenetwrk** [comment]
I was just looking into building one for Hydra, thanks for working on it Porkie. One edit I noticed is the default port for hydra is 5075, but you have it listed as 5050 in the tooltip. You may want to edit that to reduce confusion. 5050 would conflict with CouchPotato if someone read that and tried to use it.

**Comment by porkie02** [comment]
thanks Ill fix that now.

**Comment by schakrava** [comment]
Thanks @porkie02, happy to merge!

**Pull request merged**
