### PR TITLE
Adds Piwigo - piwigo.org

### PR DESCRIPTION
**Pull request by geongeorge**
### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: Pwigo
- website: https://piwigo.org/

- description: Piwigo is open source photo management software.

### Information on docker image
- docker image: https://github.com/linuxserver/docker-piwigo
- is an official docker image available for this project?: yes

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [x] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

### Working using docker run:

I do not know how to incorporate a timezone selector using the json config. But this can be changed later.

```
docker run -d \
  --name=piwigo \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 9000:80 \
  -v /config \
  -v /gallery \
  --restart unless-stopped \
  lscr.io/linuxserver/piwigo:latest
```

image

### CODE REVIEW

**Comment by phillxnet** [comment]
@geongeorge Hello there, and thanks for this contribution.
I've added a "needs review" label but form just a quick look we are missing a new requirement recently enforced by @Hooverdan96 across all our Rock-ons declaring the arch compatibility within the description.

Take a look at any other Rock-on and the following recently merged pull request to see how this is done:
https://github.com/rockstor/rockon-registry/pull/323
and:
https://github.com/rockstor/rockon-registry/pull/310

This way we ensure all our Rock-ons indicate their architecture compatibility: or at least it's known state at time of last commit.
We now support running on ARM64 architecture so it's important we have arch compatibility notes within our Rock-on descriptions. And unsurprisingly given the projects the used image looks to be arm64 compatible:
https://hub.docker.com/r/linuxserver/piwigo/tags

This little addition should help to speed up the review.

Thanks again for submitting this project as a Rock-on. It looks like a perfect candidate.

**Comment by geongeorge** [comment]
@phillxnet Thank you I'll add that!
There is one more issue I'm having. For this, to work it needs a MySQL database. To be configured after installation. I don't think Postgres works. Should I add that as a rock as well?

**Comment by phillxnet** [comment]
@geongeorge Thanks.
Re:
> Should I add that as a rockon as well?

That's a tricky one as we do prefer for Rock-ons to be as self contained as possible. Tying a few together is possible and we even have in our new v4 offering Rock-nets (https://rockstor.com/docs/interface/system/network.html#docker-network-rocknet) that may be of interest here but it would be better if we can have a more plug (read install) and play arrangement on this Rock-on. If possible. Otherwise it would be nice to have some kind of documentation to guide folks through the far more complex multi-Rock-on arrangement then necessary. With some indication of this documentation in the description. Or at minimum a note to an MySQL Rock-on instance requirement.

@Hooverdan96 & @FroggyFlox could you chip in on this one possibly as you are both more familiar with the Rock-ons system than myself currently. I'll likely get refreshed again soon however.

But by all means do consider adding a MySQL database Rock-on to complement our Postgres ones. Ideally favour official images or linuxserver.io if need be. And multi arch (amd64 & arm64) is also preferred.

**Comment by Hooverdan96** [comment]
@geongeorge. Based on #334, should this pull request then be closed?

**Comment by phillxnet** [comment]
Closing as per @Hooverdan96 comment in the context of @geongeorge comment here: https://github.com/rockstor/rockon-registry/pull/334#issuecomment-1171470122

> Hi @phillxnet I got stuck with the pull request for Piwigo, Found an alternate project.
> This container is 100% self-contained. Would be amazing if you can merge after reviewing

@Hooverdan96 has now done a review of the above referenced PiGallery2 Rock-ons pull request and as you say it looks like a better candidate than this one.

Closing here for tidy-up and due to there now being a follow-up better option.

**Pull request closed without merging**
