### PR TITLE
Update duplicati Rockon

### LINKED ISSUE #404: duplicati Rockon Environment Variables
Hi,
I tried installing the duplicati Rockon.
The webui was not reachable.
I did one test and my result was that `SETTINGS_ENCRYPTION_KEY` env var needs to be added.
See: https://docs.linuxserver.io/images/docker-duplicati/
Without it the container did not start correctly.

### PR DESCRIPTION
**Pull request by Hooverdan96**
Fixes #404  .

- no changes to docker image and existing settings.
- added required database encryption key environment variable
- cleaned up description and additional instructions

### Checklist
- [X] Passes [JSONlint](https://jsonlint.com) validation
- [X] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [X] `"description"` object lists and links to the docker image used
- [X] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [X] `"website"` object links to project's main website

### CODE REVIEW

**Comment by Hooverdan96** [comment]
Quick Test with the additional environment variable added in:

image

WebUI comes up, using `changeme` as default password and subsequently change it in the user settings (first option).

image

Adding additional shares for backup purposes - turn off Rockon, add shares, bring Rockon back up.
image

The new folders are now visible when attempting to create a backup:

image

Executed a backup and restore successfully. Simplest is if the folder/content ownership is set to the same PUID/PGID as for the duplicati container.

**Comment by Hooverdan96** [comment]
@BrokenOnedroid may be you can test whether the uninstall/reinstall will work properly now.

**Comment by BrokenOnedroid** [comment]
@Hooverdan96 give me a day or two.

**Comment by BrokenOnedroid** [comment]
@Hooverdan96
installing the current Rockon-version:
duplicati_without

Using this PR:
duplicati_with

Settings asking for Encryption-Key:
duplicati_settings

Can add volumes:
duplicati_backup

Using a cloned share of my used rockon config (development-tag):
duplicati_own

I dont's see any problems.
A already encrypted database can be used with the correct `SETTINGS_ENCRYPTION_KEY`.

**Comment by Hooverdan96** [comment]
@BrokenOnedroid, thanks for testing this! @phillxnet from my perspective the change is functional then and could be merged, if you agree.

**Comment by phillxnet** [comment]
I'm wondering if there has been another upstream update here breaking what was just submitted. Duplicati version indicates the same as per @BrokenOnedroid detailed report though. But this may be a docker packaging thing. When I install, using a fresh (empty) share, and dedicated OS user (with share owned by this user and group 'users') I get a failed login:

Web-UI-no-auth

With the following url showing in browser: http://rleap15-6.lan:8200/ngax/index.html

- Reload: results in the same:
- Login: Asks for a password. Encryption key fails as expected.

@BrokenOnedroid & @Hooverdan96 Have either of you tried this Rock-on in the pull request form using a clean share as the config, and maybe also without authenticating cookie held in browser cache?

Or have I (as is entirely likely) missed something obvious. As currently this looks to be an unusable Rock-on at least from a clean install point of view. But the reported breakage re encryption key is not evident: so we have a win of sorts.

```
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: [migrations] started
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: [migrations] no migrations found
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: ───────────────────────────────────────
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: 
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       ██╗     ███████╗██╗ ██████╗
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       ██║     ██╔════╝██║██╔═══██╗
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       ██║     ███████╗██║██║   ██║
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       ██║     ╚════██║██║██║   ██║
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       ███████╗███████║██║╚██████╔╝
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       ╚══════╝╚══════╝╚═╝ ╚═════╝
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: 
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:    Brought to you by linuxserver.io
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: ───────────────────────────────────────
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: 
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: To support LSIO projects visit:
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: https://www.linuxserver.io/donate/
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: 
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: ───────────────────────────────────────
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: GID/UID
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: ───────────────────────────────────────
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: 
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: User UID:    1018
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: User GID:    100
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: ───────────────────────────────────────
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: Linuxserver.io version: v2.1.0.2_beta_2024-11-29-ls228
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: Build-date: 2024-12-14T03:56:45+00:00
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: ───────────────────────────────────────
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:     
Dec 17 17:03:02 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: [custom-init] No custom files found, skipping...
Dec 17 17:03:03 rleap15-6 avahi-daemon[731]: Joining mDNS multicast group on interface veth244b5c3.IPv6 with address fe80::2428:c2ff:fe9b:7f3c.
Dec 17 17:03:03 rleap15-6 avahi-daemon[731]: New relevant interface veth244b5c3.IPv6 for mDNS.
Dec 17 17:03:03 rleap15-6 avahi-daemon[731]: Registering new address record for fe80::2428:c2ff:fe9b:7f3c on veth244b5c3.*.
Dec 17 17:03:05 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: Inside getter
Dec 17 17:03:07 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: Connection to localhost (127.0.0.1) 8200 port [tcp/*] succeeded!
Dec 17 17:03:07 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: [ls.io-init] done.
Dec 17 17:03:08 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: Server has started and is listening on port 8200
Dec 17 17:03:17 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]: fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Dec 17 17:03:17 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       An unhandled exception has occurred while executing the request.
Dec 17 17:03:17 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       Duplicati.WebserverCore.Exceptions.UnauthorizedException: Authorization failed due to missing cookie.
Dec 17 17:03:17 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:          at Duplicati.WebserverCore.Endpoints.V1.Auth.<>c.<<Map>b__3_0>d.MoveNext()
Dec 17 17:03:17 rleap15-6 linuxserver/duplicati:latest/duplicati-lsio[16236]:       --- End of stack trace from previous location ---

```

Reproducible on latest Firefox and Chromium based browser. No existing cookies on either.

```
rleap15-6:~ # docker ps
CONTAINER ID   IMAGE                          COMMAND   CREATED          STATUS          PORTS                                       NAMES
cfd8adba9baf   linuxserver/duplicati:latest   "/init"   12 minutes ago   Up 12 minutes   0.0.0.0:8200->8200/tcp, :::8200->8200/tcp   duplicati-lsio
```

## test install config

Resource type  |	Internal Reference  |	External Reference / Configured value 
 -- | -- | --
Share |	/config	| duplicati-config
Port |	8200 |	8200
Env	| PUID	| 1018  
Env	| PGID	| 100  
Env	| SETTINGS_ENCRYPTION_KEY |	testpass12345678  

Also tried in chromium variant using: "Open link in private window" on Rock-on Web-UI button.

Could be be a slug update of sorts required? But my initial URL is as expected: http://rleap15-6.lan:8200/

I am, as such, reluctant to merge this as-is. But it does, as reported, address an existing install failure.

@Hooverdan96 Let me know if you need me to merge this anyway as it may make it easier to go-from-here and fix the next thing as it were. Unless of course it's between the floor and my contact with the keyboard.

**Comment by Hooverdan96** [comment]
I think you did everything correctly. During my test I should have been more explicitly showing on how to initially get into duplicati.

> With the following url showing in browser: http://rleap15-6.lan:8200/ngax/index.html
> Reload: results in the same:
> Login: Asks for a password. Encryption key fails as expected.

Due to the nature of Duplicati it generates its own password that you usually retrieve via connecting into the docker container (as far as I remember). Linuxserver made this easier by essentially changing it to `changeme`, if you don't use the explicit password parameter (which this Rockon doesn't).

image

So after the first message you saw, and when then selecting the login again, by using the `changeme` password will get you in, and then it can be changed in the settings.

That apparently was always the case for this docker image (other linuxserver ones follow a similar approach for passwords).


I can add the `changeme` detail to the description. I think not having the password exposed/clear text is probably not a bad thing from a security  standpoint...

**Comment by phillxnet** [comment]
@Hooverdan96 Re:

> I can add the `changeme` detail to the description.

That would be great, and I think I remember you explaining this to me before. My apologies.

I see that you have now already popped in a commit. I'll go re-test and report here accordingly.

**Review by phillxnet — APPROVED** [review]
@Hooverdan96 Thanks for seeing this through to conclusion. And thanks also to @BrokenOnedroid for the additional testing.

OK, having now retried post your additional initial setup info I see:

duplicati-change-me-info

Web-UI now all good, and:

- Settings: **Change server passphrase** tick and enter

Worked to reset pass: testing involved explicitly logging out and back-in.

Web-UI-access-post-passphrase-change

**Comment by phillxnet** [comment]
PRODUCTION published

**Pull request merged**
