### PR TITLE
New VPN Rockon Based on WireGuard

### PR DESCRIPTION
**Pull request by Hooverdan96**
Simple setup WireGuard + Admin UI container

### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: WireGuard Easy
- website: https://wireguard.com
- description: Simple container for setting up a VPN server, includes an easy to use administration WebUI.

### Information on docker image
- docker image: [https://hub.docker.com/r/weejewel/wg-easy
- No. The benefit of this implementation is that this Wireguard server comes with a WebUI that allows convenient setup of a client using a QR code (simpler than, say, the OpenVPN Rockon). By exposing variables like DNS, it can easily be integrated and used alongside pi-hole, etc.

### Checklist
- [X] Passes [JSONlint](https://jsonlint.com) validation
- [X] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [X] `"description"` object lists and links to the docker image used
- [X] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [X] `"website"` object links to project's main website

### CODE REVIEW

**Comment by Hooverdan96** [comment]
Installation example:

image

After installation starting up WebUI and logging on with specified password:

image

Creating the settings for a new VPN client is as simple as naming it, and provide the new client with e.g. a QR code:

image


on iPhone, e.g. use the available WireGuard app, which allows for scanning a QR code. On Windows computer there is a free client app available (like WireguardPro) for which one can export the config file from the WebUI and import.

image

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for submitting this. It looks like a really nice Rock-on.

**Comment by phillxnet** [comment]
@Hooverdan96 I've just tested this, as if merged, from a local repo and I get the following:
```
[14/Dec/2023 15:24:28] ERROR [storageadmin.util:41] (Error while processing Rock-on profile at (http://build.lan/rockons/WireGuardEasy.json).). Lower level exception: (Expecting ':' delimiter: line 86 column 344 (char 2989)).
[14/Dec/2023 15:24:28] ERROR [storageadmin.util:45] Exception: Expecting ':' delimiter: line 86 column 344 (char 2989)
Traceback (most recent call last):
  File "/opt/rockstor/.venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 86 column 344 (char 2989)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 503, in _get_available
    meta_cfg.update(cur_res.json())
                    ^^^^^^^^^^^^^^
  File "/opt/rockstor/.venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting ':' delimiter: line 86 column 344 (char 2989)
```
Looks like we could also do with a pr format checker in this repo re JSON :).

Double checking in an online linter: http://jsonlint.vearne.cc/
```
Error: Parse error on line 86:
...4 architecture.</p>",		"ui": {			"slug
-----------------------^
Expecting ':', got ','

```
Which looks to be pretty similar. Something it trying to tell us to get our GitHub actions in order re basic formatting checks :) .

**Comment by phillxnet** [comment]
From a quick look at the raw file, it looks to be missing the description tag, likely lost in some merge of sorts!

**Comment by Hooverdan96** [comment]
argh! As always, thanks for your due diligence. I definitely json linted it, but since that's always a copy/past action on my part, I must have screwed up something with the final commit. I'll take care of that.

One the other hand, do we need this at all, since @FroggyFlox now introduced the wireguard setup as a native functionality (albeit still in testing channel?

In any case, I'll fix the json ...

**Comment by FroggyFlox** [comment]
I just wanted to chime in on the following:

> One the other hand, do we need this at all, since @FroggyFlox now introduced the wireguard setup as a native functionality (albeit still in testing channel?

I personally think we do as this Rock-On and Tailscale address two different possible uses or, most likely, two different types of users. Some may use Tailscale to remotely access their Rockstor box, while other may prefer to use their own, or an existing, WireGuard setup.

**Comment by Hooverdan96** [comment]
ok, that makes sense to me too. I hopefully updated the json correctly this time around

**Review by phillxnet — APPROVED** [review]
@Hooverdan96 Thanks for sumitting this, it looks to be a great addition. I've only tested install, on/off, uninstall - reinstall, persistence through reboot, and Web-UI button/loging. And have added a single client. But I understand you've proven actual function. So I'll go ahead and merge.

Quite the nice addition actually.

## Installed

wireguard-rockon-Installed

## Web-UI
pr346

**Comment by phillxnet** [comment]
PR product PRODUCTION published.

**Pull request merged**
