### PR TITLE
Remove Bitcoin Rockon

### LINKED ISSUE #349: Remove Bitcoin Rock-on
The time has passed for this Rock-on. By way of updating, and refining, our Rock-on selection it has been ear-marked for removal.

### PR DESCRIPTION
**Pull request by Hooverdan96**
Fixes #349.

### General information on project
This pull request proposes to remove the Bitcoin Rockon.

### Checklist
- [X] Passes [JSONlint](https://jsonlint.com) validation
- [X] Entry remove from `root.json`
- [ ] `"description"` object lists and links to the docker image used
- [ ] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [ ] `"website"` object links to project's main website

### CODE REVIEW

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for seeing to this, much appreciated.
Would you mind squashing these two commits into one? It can then server as a cleaner, more recent example of how rock-ons are removed. We have a few that likely should be weeded out now.

**Comment by Hooverdan96** [comment]
Here you go. Hope that works.

**Comment by Hooverdan96** [comment]
@phillxnet @FroggyFlox can you do the honors of merging this, so we can have this rockon cleared out of the repository as was proposed earlier?

**Comment by phillxnet** [comment]
@Hooverdan96 Sorted as requested.

Incidentally let me know when you want me to push this repo to PRODUCTION again.

**Comment by phillxnet** [comment]
PR product PRODUCTION published.

**Pull request merged**
