### PR TITLE
bare os server set #94

### PR DESCRIPTION
**Pull request by phillxnet**
In development/draft/untested PR intended to ease collaboration as this one is a bit of a monster currently. And may require some rockstor-core Rock-on improvements to accommodate.

Relates to #94

### CODE REVIEW

**Comment by phillxnet** [comment]
# Testing to-date:

> Invalid environment variable (DB_ADMIN_PASSWORD).

**Comment by phillxnet** [comment]
@FroggyFlox & @Hooverdan96 what am I missing here? I'm still getting:

> Invalid environment variable (DB_ADMIN_PASSWORD).

directly after finishing the Rock-on setup wizard. No other logs debug or otherwise.

BareOS-server-set-install-wizard-summary

**Comment by FroggyFlox** [comment]
I'm worried this is a symptom of the "invalid environment variable" issue: https://github.com/rockstor/rockstor-core/issues/1588

**Comment by phillxnet** [comment]
Using Draft PR branch https://github.com/rockstor/rockstor-core/issues/1588 as a fix to the prior Rock-on install blocker of:

> Invalid environment variable (DB_ADMIN_PASSWORD).

We have this draft Rock-on installing (but not yet functional) with the following **docker networks** auto-created:

```
[13/Aug/2024 19:15:31] DEBUG [system.docker:190] the network bareos-director-to-db was NOT detected, so create it now.
[13/Aug/2024 19:15:31] DEBUG [system.osi:262] Running command: /usr/bin/docker network create bareos-director-to-db
[13/Aug/2024 19:15:32] DEBUG [system.osi:262] Running command: /usr/bin/docker network connect bareos-director-to-db bareos-director
[13/Aug/2024 19:15:33] DEBUG [system.osi:262] Running command: /usr/bin/docker network connect bareos-director-to-db bareos-db
[13/Aug/2024 19:15:33] DEBUG [system.docker:190] the network bareos-director-to-storage was NOT detected, so create it now.
[13/Aug/2024 19:15:33] DEBUG [system.osi:262] Running command: /usr/bin/docker network create bareos-director-to-storage
[13/Aug/2024 19:15:34] DEBUG [system.osi:262] Running command: /usr/bin/docker network connect bareos-director-to-storage bareos-director
[13/Aug/2024 19:15:34] DEBUG [system.osi:262] Running command: /usr/bin/docker network connect bareos-director-to-storage bareos-storage
[13/Aug/2024 19:15:35] DEBUG [system.docker:190] the network bareos-director-to-webui was NOT detected, so create it now.
[13/Aug/2024 19:15:35] DEBUG [system.osi:262] Running command: /usr/bin/docker network create bareos-director-to-webui
[13/Aug/2024 19:15:35] DEBUG [system.osi:262] Running command: /usr/bin/docker network connect bareos-director-to-webui bareos-director
[13/Aug/2024 19:15:35] DEBUG [system.osi:262] Running command: /usr/bin/docker network connect bareos-director-to-webui bareos-webui
[13/Aug/2024 19:15:37] DEBUG [storageadmin.views.rockon_helpers:210] Set rock-on 79 state to installed
[13/Aug/2024 19:15:37] INFO [storageadmin.tasks:64] Task [install], id: 8b72981a-0505-4549-af79-3837f656f6b7 completed OK
```

**Comment by phillxnet** [comment]
Superseded by PR #383

**Pull request closed without merging**
