### PR TITLE
Dropbox

### PR DESCRIPTION
**Pull request by coleberhorst**
Installed json file and tested. 

`docker logs dropbox` to get link to link to my dropbox account in browser. Shortly thereafter `docker exec -it dropbox dropbox status` reported dropbox was syncing.

I have enabled the necessary options for local lan syncing and am in the process of testing this.

### CODE REVIEW

**Comment by coleberhorst** [comment]
after a bit dropbox stops syncing and outputs as status:
You're using an old version of Dropbox. Please update to the latest version to continue using Dropbox.
https://www.dropbox.com/downloading?from_client=True
Any ideas?

**Comment by coleberhorst** [comment]
Ok new commits fix updating issue and dropbox syncs well again.

**Comment by schakrava** [comment]
works for me. Thank you @coleberhorst , really appreciate your contributions

**Comment by coleberhorst** [comment]
Thanks :)

I gotta pay @phillxnet  back for all his free tech support somehow xD

**Comment by schakrava** [comment]
@coleberhorst @phillxnet gratipay? :)

Great to have you in the community @coleberhorst, thanks for giving back with your contributions.

**Pull request merged**
