### PR TITLE
Mylar

### PR DESCRIPTION
**Pull request by alazare619**
Similar to Sonarr, Radarr, Sickgear, Headphones but for Comics

### CODE REVIEW

**Comment by alazare619** [comment]
Just tested and it launches and runs amazingly.

**Comment by alazare619** [comment]
@magicalyak

**Comment by schakrava** [comment]
I managed to get around to it before @magicalyak :)
Works great, neat app. Thank you @alazare619 !

**Comment by alazare619** [comment]
@suman don't miss the radarr one or ombi both have been tested and working
thanks for the mergers

**Comment by magicalyak** [comment]
Thanks! It's been crazy recently for me but I should be reviewing things a bit quicker in the near future.

**Pull request merged**
