### PR TITLE
initial commit of minecraft.json

### PR DESCRIPTION
**Pull request by legbandj**
Initial commit. Adds a docker container for minecraft.

### CODE REVIEW

**Comment by phillxnet** [comment]
@legbandj Thanks for the submission. Looks like a pretty popular docker image (8M) and the json check out OK at https://jsonlint.com/.

Can you confirm that this rock-on has worked successfully for you via the local /opt/rockstor/rockons-metastore/  install option?

Cheers.

**Comment by FroggyFlox** [comment]
It installs fine on my Rockstor 3.9.2-40 install. I didn't test the connection from a minecraft client, though, but I couldn't see any blocking errors on the logs. The only error I encountered was due to my very low-powered hardware used to test it (see at the very bottom of this post).

Although I'm not familiar with how Minecraft servers work, it seems to me that it would be beneficial to add a volume binding to make data persistent, including server configurations, mods, and maybe even the worlds themselves. See the container's documentation section about it:

> Using the /data volume
> This is the easiest way if you are using a persistent /data mount.
> 
> To do this, you will need to attach the container's /data directory
> (see "Attaching data directory to host filesystem”).
> Then, you can add mods to the /path/on/host/mods folder you chose. From the example above,
> the /path/on/host folder contents look like:
> 
> 
> /path/on/host
> ├── mods
> │   └── ... INSTALL MODS HERE ...
> ├── config
> │   └── ... CONFIGURE MODS HERE ...
> ├── ops.json
> ├── server.properties
> ├── whitelist.json
> └── ...

```
Sep 29 06:36:05 rockdev systemd[1]: Starting Cleanup of Temporary Directories...
Sep 29 06:36:10 rockdev systemd[1]: Started Cleanup of Temporary Directories.
Sep 29 06:36:22 rockdev kernel: docker0: port 1(vethb88005a) entered blocking state
Sep 29 06:36:22 rockdev kernel: docker0: port 1(vethb88005a) entered disabled state
Sep 29 06:36:22 rockdev kernel: device vethb88005a entered promiscuous mode
Sep 29 06:36:22 rockdev kernel: IPv6: ADDRCONF(NETDEV_UP): vethb88005a: link is not ready
Sep 29 06:36:22 rockdev NetworkManager[1639]: <info>  [1538228182.4866] manager: (veth78422a3): new Veth device (/org/freedesktop/NetworkManager/Devices/4)
Sep 29 06:36:22 rockdev NetworkManager[1639]: <info>  [1538228182.4904] manager: (vethb88005a): new Veth device (/org/freedesktop/NetworkManager/Devices/5)
Sep 29 06:36:23 rockdev kernel: eth0: renamed from veth78422a3
Sep 29 06:36:23 rockdev NetworkManager[1639]: <info>  [1538228183.9441] device (vethb88005a): carrier: link connected
Sep 29 06:36:24 rockdev kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethb88005a: link becomes ready
Sep 29 06:36:24 rockdev kernel: docker0: port 1(vethb88005a) entered blocking state
Sep 29 06:36:24 rockdev kernel: docker0: port 1(vethb88005a) entered forwarding state
Sep 29 06:36:24 rockdev kernel: IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
Sep 29 06:36:23 rockdev NetworkManager[1639]: <info>  [1538228183.9450] device (docker0): carrier: link connected
Sep 29 06:36:24 rockdev avahi-daemon[1636]: Withdrawing workstation service for veth78422a3.
Sep 29 06:36:25 rockdev avahi-daemon[1636]: Registering new address record for fe80::786b:24ff:fe1f:3c30 on vethb88005a.*.
Sep 29 06:36:25 rockdev avahi-daemon[1636]: Registering new address record for fe80::42:15ff:fe29:8940 on docker0.*.
Sep 29 06:36:26 rockdev 499dd45c7ead[2536]: usermod: no changes
Sep 29 06:36:27 rockdev 499dd45c7ead[2536]: Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    1 1000     1000            16 Sep 29 06:36 /data'
Sep 29 06:36:27 rockdev 499dd45c7ead[2536]: Checking version information.
Sep 29 06:36:28 rockdev 499dd45c7ead[2536]: Checking type information.
Sep 29 06:36:28 rockdev 499dd45c7ead[2536]: Downloading minecraft_server.1.13.1.jar ...
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Creating server.properties in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting server-port to '25565' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting motd to 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting allow-nether
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting announce-player-achievements
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting enable-command-block
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting spawn-animals
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting spawn-monsters
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting spawn-npcs
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting generate-structures
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting view-distance
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting hardcore
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting snooper-enabled
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting max-build-height
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting force-gamemode
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting max-tick-time
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting enable-query
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting query.port
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting enable-rcon to 'true' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting rcon.password to 'minecraft' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting rcon.port to '25575' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting max-players
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting max-world-size
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting level-name to 'world' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting level-seed
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting pvp to 'true' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting generator-settings
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting online-mode to 'true' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skip setting allow-flight
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting level type to DEFAULT
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting level-type to 'DEFAULT' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting difficulty to '1' in /data/server.properties
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Skipping JSON check. No files present.
Sep 29 06:36:32 rockdev 499dd45c7ead[2536]: Setting initial memory to 1G and max to 1G
Sep 29 06:36:50 rockdev 499dd45c7ead[2536]: [13:36:50] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
Sep 29 06:36:50 rockdev 499dd45c7ead[2536]: [13:36:50] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
Sep 29 06:36:50 rockdev 499dd45c7ead[2536]: [13:36:50] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
Sep 29 06:36:50 rockdev 499dd45c7ead[2536]: [13:36:50] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
Sep 29 06:36:50 rockdev 499dd45c7ead[2536]: [13:36:50] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
Sep 29 06:36:51 rockdev 499dd45c7ead[2536]: [13:36:51] [main/INFO]: Loaded 0 recipes
Sep 29 06:36:51 rockdev 499dd45c7ead[2536]: [13:36:51] [main/INFO]: Loaded 0 advancements
Sep 29 06:36:51 rockdev 499dd45c7ead[2536]: [13:36:51] [Server thread/INFO]: Starting minecraft server version 1.13.1
Sep 29 06:36:51 rockdev 499dd45c7ead[2536]: [13:36:51] [Server thread/INFO]: Loading properties
Sep 29 06:36:51 rockdev 499dd45c7ead[2536]: [13:36:51] [Server thread/INFO]: Default game type: SURVIVAL
Sep 29 06:36:51 rockdev 499dd45c7ead[2536]: [13:36:51] [Server thread/INFO]: Generating keypair
Sep 29 06:36:52 rockdev 499dd45c7ead[2536]: [13:36:52] [Server thread/INFO]: Starting Minecraft server on *:25565
Sep 29 06:36:52 rockdev 499dd45c7ead[2536]: [13:36:52] [Server thread/INFO]: Using epoll channel type
Sep 29 06:36:53 rockdev 499dd45c7ead[2536]: [13:36:53] [Server thread/INFO]: Preparing level "world"
Sep 29 06:36:53 rockdev 499dd45c7ead[2536]: [13:36:53] [Server thread/INFO]: Found new data pack vanilla, loading it automatically
Sep 29 06:36:53 rockdev 499dd45c7ead[2536]: [13:36:53] [Server thread/INFO]: Reloading ResourceManager: Default
Sep 29 06:36:56 rockdev 499dd45c7ead[2536]: [13:36:56] [Server thread/INFO]: Loaded 524 recipes
Sep 29 06:38:06 rockdev 499dd45c7ead[2536]: [13:38:00] [Server thread/INFO]: Loaded 571 advancements


Sep 29 06:41:35 rockdev 499dd45c7ead[2536]: [13:41:34] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
Sep 29 06:41:37 rockdev 499dd45c7ead[2536]: [13:41:37] [Server thread/INFO]: Preparing spawn area: 0%
Sep 29 06:41:38 rockdev 499dd45c7ead[2536]: [13:41:38] [Server thread/INFO]: Preparing spawn area: 0%
(...)
Sep 29 06:46:10 rockdev 499dd45c7ead[2536]: [13:46:10] [Server thread/INFO]: Preparing spawn area: 96%
Sep 29 06:46:10 rockdev 499dd45c7ead[2536]: [13:46:10] [Server thread/INFO]: Preparing spawn area: 100%
Sep 29 06:46:10 rockdev 499dd45c7ead[2536]: [13:46:10] [Server thread/INFO]: Time elapsed: 276187 ms
Sep 29 06:46:11 rockdev 499dd45c7ead[2536]: [13:46:11] [Server thread/INFO]: Done (557.720s)! For help, type "help"
Sep 29 06:46:11 rockdev 499dd45c7ead[2536]: [13:46:11] [Server thread/INFO]: Starting remote control listener
Sep 29 06:46:12 rockdev 499dd45c7ead[2536]: [13:46:12] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
Sep 29 06:46:35 rockdev 499dd45c7ead[2536]: [13:46:35] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 22184ms or 443 ticks behind
Sep 29 06:47:51 rockdev 499dd45c7ead[2536]: [13:47:50] [Server Watchdog/FATAL]: A single server tick took 62.54 seconds (should be max 0.05)
Sep 29 06:47:51 rockdev 499dd45c7ead[2536]: [13:47:50] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
Sep 29 06:47:52 rockdev 499dd45c7ead[2536]: [13:47:51] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 61614ms or 1232 ticks behind
Sep 29 06:47:52 rockdev 499dd45c7ead[2536]: [13:47:52] [Server Watchdog/ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2018-09-29_13.47.52-server.txt
Sep 29 06:47:53 rockdev 499dd45c7ead[2536]: [13:47:53] [Server Shutdown Thread/INFO]: Stopping server
Sep 29 06:47:53 rockdev 499dd45c7ead[2536]: [13:47:53] [Server Shutdown Thread/INFO]: Saving players
Sep 29 06:47:53 rockdev 499dd45c7ead[2536]: [13:47:53] [Server Shutdown Thread/INFO]: Saving worlds
Sep 29 06:47:53 rockdev 499dd45c7ead[2536]: [13:47:53] [Server Shutdown Thread/INFO]: Saving chunks for level 'world'/minecraft:the_nether
Sep 29 06:47:55 rockdev 499dd45c7ead[2536]: 2018-09-29 13:47:55,854 Server Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
Sep 29 06:48:13 rockdev 499dd45c7ead[2536]: 2018/09/29 06:48:13 Done
```

**Comment by legbandj** [comment]
It does work just fine via the /opt/rockstor/rockons-metastore/ option.

I had originally installed directly with docker, but removed the install
and a reinstall via the metastore works as expected.

**Comment by legbandj** [comment]
> It installs fine on my Rockstor 3.9.2-40 install. I didn't test the connection from a minecraft client, though, but I couldn't see any blocking errors on the logs. The only error I encountered was due to my very low-powered hardware used to test it (see at the very bottom of this post).
> 
> Although I'm not familiar with how Minecraft servers work, it seems to me that it would be beneficial to add a volume binding to make data persistent, including server configurations, mods, and maybe even the worlds themselves. See the container's documentation section about it:
> 
> > Using the /data volume
> > This is the easiest way if you are using a persistent /data mount.
> > To do this, you will need to attach the container's /data directory
> > (see "Attaching data directory to host filesystem”).
> > Then, you can add mods to the /path/on/host/mods folder you chose. From the example above,
> > the /path/on/host folder contents look like:
> > /path/on/host
> > ├── mods
> > │   └── ... INSTALL MODS HERE ...
> > ├── config
> > │   └── ... CONFIGURE MODS HERE ...
> > ├── ops.json
> > ├── server.properties
> > ├── whitelist.json
> > └── ...
> 

Any idea how to do that in the json? I'm newish to setting up containers, and had done that in the past via portainer.

**Comment by FroggyFlox** [comment]
Sure @legbandj !
Have a look at the README file and its section on the `"volumes"` object:
https://github.com/rockstor/rockon-registry#volume-object

It would basically consist in adding the following at the same level as the "ports" or "environment" objects:
```
"volumes": {
                    "/data": {
                        "description": "Choose a Share for the Minecraft server data, including configuration, mods, etc... (Insert appropriate description here).",
                        "label": "Data storage"
                    }
}
```

**Comment by phillxnet** [comment]
@legbandj Thanks for this long awaited Rock-on submission, we did have a prior submission of PocketMine from @magicalyak a long time back but it had some stability issues.

Linking for context:
"Pull for fork - add PocketMine" #49

Your chosen docker image looks to be well updated (7 day ago) and near enough a defacto official one given it's now 10M use so given @FroggyFlox's keen suggestion re persistence of storage has now been addressed I'm going to commit this as is.

Apologies to all if this is under tested but given our backlog I think it best we get it in so it can be tested further. We can always fix by an additional pr and it's a 'non critical' application anyway.

Json format checks out after the 'add data volume' commit.

@FroggyFlox Thanks for assisting with getting this Rock-on into usable shape re the persistence volume contribution.

**Comment by FroggyFlox** [comment]
I only now noticed I never tested it again since your last commit @legbandj; sorry about that.

The `/data` volume addition works as expected in both Rockstor-3.9.1-16 and Tumbleweed-20190126 with Rockstor updated to the most recent update branch.

**Comment by phillxnet** [comment]
Linking to related root.json update issue to add the required entry:
"missing root.json entries" #171

**Pull request merged**
