### PR TITLE
owncloud HTTPS .json file

### PR DESCRIPTION
**Pull request by Slowhand93**
Please merge this file to the branch. It's the official owncloud image with SSL.
Forum post: [https://forum.rockstor.com/t/owncloud-offical-image-guide/]

### CODE REVIEW

**Comment by schakrava** [comment]
Thank you @Slowhand93. The file looks good to me, but it doesn't work unless you follow the steps you've documented in your [guide](https://forum.rockstor.com/t/owncloud-ssl-offical-image-guide/1778), correct?

**Comment by Slowhand93** [comment]
@schakrava Yes thats correct.

**Comment by schakrava** [comment]
@Slowhand93 in that case, we should add the link to those steps in the "more_info" of the rock-on.

**Comment by Slowhand93** [comment]
@schakrava Ok it's done! Thank you!

**Comment by schakrava** [comment]
Thank you! @Slowhand93 Happy to merge.

**Comment by phillxnet** [comment]
@ahlongas07 Nice find. And Thanks for the report.
Do you fancy submitting a pull request for this updated image change, and any other differences this may make to this Rock-on.
It would also be good if you created a new issue to address this image update requirement as this issue is now closed and it would then be a more focused topic that is more likely to be picked up; if you don't end up submitting the fix yourself of course.
Cheers.

We have the following docs that may help:
https://rockstor.com/docs/contribute/contribute_rockons.html
although that pertains to new Rock-ons but should be of help.
We also have the Readme in this repo.

**Pull request merged**
