### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by porkie02**
Added NZBHydra

### CODE REVIEW

**Comment by phillxnet** [comment]
@porkie02 Hello again, and thanks again for getting this submitted:

Just a quick note on this pr, could you change the pr title to reflect what you have added, this helps with attribution and in keeping track of what happened when, ie "add NZBHydra rockon" or what ever. Also good idea to do the same with commit messages going forward, ie make them as specific as possible.
And another rather trivial but nevertheless helpful thing would be to remove the tab characters and use spaces instead so that the whole file uses only blocks of 4 spaces. I see tabs in lines 21, 28, 31, 45, and 46. Seems trivial but does help with assessing the structure and consequently with future maintenance.

No worries otherwise though.

**Comment by phillxnet** [comment]
@porkie02 I see you have just added a second rockon to this same pr. It is much preferred that you do a separate pull request for each rock-on you wish to add. 
I suspect that what has happened here is that you are working in your own forked master repository.

To keep changes separated from one another you can create git branches and keep all the changes associated with each rockon / pr in each of the relevant branches.  You may find it easier to take a copy of the files you have added, delete this pr, then add those files each in turn to their respective git branches. That way they stay divided. Then you can submit a pull request from each of the independant branches. Also once merged you can delete your own branch and keep thinks tidy.

Hope that helps.

These branching details are specified in the README.md file in this repo.

This Branching really helps as then you can work on independent rock-ons simultaneously as you appear to be doing.

**Comment by porkie02** [comment]
opps ok sorry

**Comment by phillxnet** [comment]
From the looks of it you will need now need 3 branches:
NZBHydra_rockon
Jackett_rockon
and now
Muximux_rockon

And now worries as this git stuff is quite tricky.

Remember that you can always start from the beginning by deleting your entire fork (obviously after you have taken copeis of all relevant changes) then re-fork so that each of your branches is then an exact copy of the upstream master (the official rockon-repo). This way the changes involved in adding a specific rock-on are those required to be made to add that same rock-on the rockstor master branch. Hope that makes sense.

**Comment by porkie02** [comment]
Sure Ill have a go now at it this afternoon, hopefully ill sort it. :)

**Comment by phillxnet** [comment]
So one branch from current master for each rock-on and then a pull request from each of those branches in turn.
3 rock-ons 3 branches 3 pull requests.
As you will have master forked then your own GitHub repo will have 4 concurrent versions, if master is included of course.

i think the idea is that you never make changes to master directly, always work in a feature branch, or in this case a rock-on specific branch. Then once it's up streamed (merged into the upstream master) you can always update your own master to reflect that of upstream. Ready to do new branches from that updated master. @schakrava has done quite a nice job in that README.md, seems like a load of steps but without them stuff can get pretty messy.

No rush as once you get this right, or at least so that it works for you and others, then it will really help ease the process and it looks like you have a pile of rock-ons mounting up as we speak.

Keeping them separate (in their own branches and prs) also gives the option for individual review, which is important as some rock-ons, docker containers, need special attention and it would be a shame for them all to be held up by just one.

See how you get on and no shame in nuke an pave, just make sure you have copied all your work out from inside the git directory before you nuke.

Hope that helps.

**Comment by phillxnet** [comment]
@porkie02  That was quick, I see now you have:
https://github.com/rockstor/rockon-registry/pull/66
https://github.com/rockstor/rockon-registry/pull/67
https://github.com/rockstor/rockon-registry/pull/68
Each from their own branch, perfect.

In which case I would say this pr is now redundant as it's contents are duplicated in the above prs.
If you agree then you could close this pr to avoid accidental confusion.

**Pull request closed without merging**
