### PR TITLE
add NodeRed rock-on

### PR DESCRIPTION
**Pull request by dontsentspem**
> To ease and accelerate the PR submission, please use the template below to provide all requested information.
> You can find guidelines on which docker image to use in the [Rockstor's documentation](http://rockstor.com/docs/contribute_rockons.html#which-docker-image-should-i-use), 
> as well as examples of proper formatting in other rock-ons ([here](https://github.com/rockstor/rockon-registry/blob/master/teamspeak3.json)
> and [here](https://github.com/rockstor/rockon-registry/blob/master/nextcloud-official.json))

Fixes # .

### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: NodeRed
- website: https://nodered.org
- description: Low-code programming for event-driven applications. This is programming tool for wiring together hardware devices, API's and online services. Alternatives are n8n.io, ioBroker, AWS  IoT & ThingsBoard.io to name a few.

### Information on docker image
- docker image: https://hub.docker.com/r/nodered/node-red
- is an official docker image available for this project?: No

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [x] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

### CODE REVIEW

**Comment by phillxnet** [comment]
@dontsentspem Thanks for the contribution. Just taking another quick look and thanks for sorting out the missing root.json entry but I don't see a link within the description to the docker image used.
I.e. In the following we see such a link in the Nginx-proxy-manager:

Node_red-pre-install

I'm also a little unsure of the man name change you just did as we already have the website link to this page (the upstream project) and given this is not an official image having the project address in the name may imply this is an official image. I know you state in the pull request test that there is no official image but they may be later.

Anyway installs fine for me in a Testing channel 'Build on openSUSE' Leap15.1 rpm install:

node-red-rock-on-installed

and survives a Rockstor reboot, and the Web-UI works post turning the Rock-on off then on again.

Docker image size:
```
leap15-1:~ # docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
nodered/node-red            latest              8c7257ff395b        11 days ago         449MB
```

Web-UI:
node-red-rock-on-web-ui

So well done. We now only have the embedded docker hub image link to get sorted in the description, as per the other relatively new Rock-ons and we are sorted, hopefully. I've also notice there is no "more_info" section? This causes a little 'i' icon to appear on the installed version of the Rock-on. Might be another nice addition if you can think of some appropriate text for that. Not a requirement though, but it's nice.

So if you are game to sort these last few bits we can take a final look and get this in.

**Comment by dontsentspem** [comment]
Hey Phill,
Did some editing.
Changed the name to Node-Red (minus sign no underscore).

Gave more_info ...took some lines from the nodered website.
Also inserted the hyperlink to the docker image.

Please let me know what you think.

Cheers,

J.

**Comment by phillxnet** [comment]
@dontsentspem I can only have a quick look now but from the following you see there is a repeat of the following text:
"docker image:"

now-with-dock-image-link

Also more my point about the docker name and it implying an official image. Again from only a quick look this does appear to be an official Node-RED docker image. If you could confirm that, if you have time, then we should be stating the image as official. For an examples of this look to the following rockons; ecoDMS 18.09, JenkinsCI, OwnCloud-Official, Nextcloud-Official etc. And take a look at the naming also. So if this is an official image, you stated otherwise in the issue text so you may have check more thoroughly than I have done just quickly just now. But if it is then we need to state that and either have the name as just "Node-RED" as that is their presentation of it on their main site, or "Node-RED-Official" which is super clunky as they already have a "-". So you could do what @FroggyFlox did in the YouTrack Rockon and just pop an "official" on it i.e. "Node-RED official". Which I like in this case. That way folks can easily pick those out. Sort of comes down to the likely hood of others doing non official docker images and us acomodating them along side official ones as they have to have unique names.

See what you think.

Info section looks good.

info-display

So take a look at shortening the main display name and following their capitalisation and at least adding indication of 'official' to the image text you just added. Assuming this is an official image.

Thanks again for chipping away at this one. All just cosmetic stuff now so pretty much there.

Oh and also from the linked GitHub page it's looking more and more like an official image to me:
https://github.com//node-red/node-red-docker

**Comment by dontsentspem** [comment]
Hi Phill,
We're almost there I figure. If I do a next container it will go much smoother :)

So the official name would be: Node-RED as it's seen throughout their website. I have changed that.
Also put "Based on the official Node-RED docker image" in the text.
And I removed the - sign so it's now Node-RED by nodered.org.

Ok?

Cheers,

J.

**Comment by 20design** [comment]
Hi @dontsentspem,

I installed the container/rockon and it's working as inteded, no issue on rockstor side, I even created an entry for it in Nginx-Proxy-Manager with a certificate.
But I am curious if you are using it with home assistant? 

Cheers,
G.

**Comment by dontsentspem** [comment]
Hi G,
At the moment I'm using it for mqtt with Domoticz. 
But as a matter of fact I'm want to transfer to Home Assistant. As always it's a snowball effect.
First I want a new durable NAS A+++. Going to build it myself ofcourse. 

In doubt to use Rockstor with rockons or use Proxmox as hypervisor and user Rockstor as a LXC.
Then I want to transfer to Home Assistant.

Cheers,

J.

**Comment by phillxnet** [comment]
@dontsentspem Apologies for the delay on this one. Should be able to given it one last try and publish shortly. I think it's pretty much there however so well done. Just been distracted with a core development issue that has a little bit of a deadline attached to it.

@20design Thanks for the double check on this one. Much appreciated.

**Comment by phillxnet** [comment]
@dontsentspem  Again apologies for the delay. But I've finally gotten around to testing this end-to-end, i.e. pre-merged into the existing rock-on repo and then have a Rockstor instance read from that repo and checked that all is as expected before actually merging proper on GitHub and publishing.

As expected all is now dandy. So thanks again for submitting and then working through this one. It looks like a really interesting project. And thank also again to @20design for chipping in here with a functional review.

**Pull request merged**
