### PR TITLE
Added DansGuardian to registry.

### PR DESCRIPTION
**Pull request by IamDH4**

### CODE REVIEW

**Comment by magicalyak** [comment]
The repo being pulled from is very lightly used, could you consider using this one which also combines squidproxy?  https://hub.docker.com/r/dry1d/dansguardian/

**Comment by IamDH4** [comment]
I will not be making any changes to this pull request. I no longer use Rockstor as it has proven to be unreliable when a disk failure occurs. Of course feel free to fork and change it.

This docker container is one I created myself because at the time all the others available did not get the job done. Such as not exposing all of the configuration files. I have this container deployed at a number of sites and it performs flawlessly. I'm not sure if the repo referenced above was part of the initial testing as it's taken you almost a year to even think about merging this pull request.

**Comment by magicalyak** [comment]
Sorry to hear that.  I only started as a reviewer today (like a few hours ago).  I apologize for the delay.

**Comment by IamDH4** [comment]
No worries. I will re-evaluate Rockstor after / if the BTRFS situation improves. Went through major data loss twice and simply cannot deploy in production.

**Pull request closed without merging**
