### PR TITLE
Adding linuxserver/netbootxyz

### PR DESCRIPTION
**Pull request by thedrjones**
Added linuxserver/netbootxyz

This is the initial version of this rock-on. I've been using it at home for a few months, linuxserver, as always, provide excellent documentation to assist in the usage. I've assumed that most rockstor users will want to sync the netbootxyz content locally (hence the custom assets port) - otherwise it can be pretty slow to pull a squashfs down to boot with for booting.

This works on CentOS (was using in April or so and have done since) and the OpenSUSE versions of RockStor.

### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: netbootxyz
- website: https://hub.docker.com/r/linuxserver/netbootxyz
- description: "Netbootxyz is a way to PXE boot various operating system installers or utilities from one place within the BIOS without the need of having to go retrieve the media to run the tool". It uses TFTP to allow the PXE images to enable network booting and provides a webserver to distribute the more complex content which can be synced from an online repository for use locally with well documented processes for it.

### Information on docker image
- docker image: https://hub.docker.com/r/linuxserver/netbootxyz
- is an official docker image available for this project?: Nothing official - you can spin your own docker image from the upstream project, but I think the linuxserver one (as with most of their images) is excellent.

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [x] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

### CODE REVIEW

**Comment by FroggyFlox** [comment]
Thanks a lot, @thedrjones  for this submission, and for a very well detailed pull request!

I was actually just looking at that image the other day following @holmesb 's submission for a Cobbler rock-on (#230) so that seems perfect. Both images seem very useful so I'm looking forward to testing it as soon as possible. I do have quite a bit of backlog unfortunately in reviewing rock-on submissions so I'm afraid it won't be that quick, but I'm hoping I'll be able to get some more time for this sort of things quickly.

In the meantime, I noticed you didn't commit the changes to the `root.json` file, so feel free to add it at your convenience.

Thanks again,

**Comment by FroggyFlox** [comment]
@thedrjones ,

As you probably have already seen in your fork, I've created a pull request there as I encountered a few blocking issues related to JSON formatting (mostly inconsistent indentations) that was unfortunately preventing our backend testing.
The rock-on itself looks very nice besides that, so I'll probably be able to merge it as soon as we have fixed these formatting issues.

Sorry again for such a delay in getting to your PR,

**Comment by thedrjones** [comment]
Thanks for those changes @FroggyFlox, PR should be in there now. The JSON file was edited in nano (not the best choice), so no surprises that I got the indentations messed up a little, next time I'll use a real editor.

**Comment by FroggyFlox** [comment]
Thanks, @thedrjones !
I've resolved a conflict with `root.json` that was related to another PR I just merged, so I'll try to give it a final test some time soon and then merge it if all still looks well.

**Review by FroggyFlox — APPROVED** [review]

**Comment by FroggyFlox** [comment]
@thedrjones ,

After a final test, all looks good in both x86_64 and Aarch64 machines, so I'm going to merge it now. I'm going to merge another PR and then I'll publish them so they should be in the list of available rock-ons in the coming days. 

Thanks a lot for your contribution, I'm really glad to see such offering in our rock-ons!

**Pull request merged**
