### PR TITLE
Plex Requests

### PR DESCRIPTION
**Pull request by Fredrik81**
Plexrequests, a simple automated way for users to request new content for Plex Users can search for content to request. Integrates with couchpotato, sonarr and sickrage etc...

### CODE REVIEW

**Comment by coleberhorst** [comment]
Can confirm this docker works.

**Comment by Fredrik81** [comment]
@schakrava ready for merge

**Comment by magicalyak** [comment]
Is this Pi-Hole or plexrequests?

**Comment by coleberhorst** [comment]
this should be plexrequests, I think it was branched improperly and had to be cleaned up afterwards, I am using the json and it works well though. alternatively I can redo the pull requests with clean branches if need be.

**Comment by Fredrik81** [comment]
Yeah i messed it up a bit with the branching. But it should be clean now if you look at the files in the pull request. Thanks for the testing @coleberhorst

**Comment by coleberhorst** [comment]
perfect, ready for merge in my opinion, been testing this one for months now.

**Comment by magicalyak** [comment]
Only need @schakrava to merge at this point.

**Pull request merged**
