### PR TITLE
add cobbler rock-on

### PR DESCRIPTION
**Pull request by holmesb**
### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: cobbler
- website: https://cobbler.github.io/
- description: Open-source PXE, DHCP, and TFTP server with webui and wide configuration manager and infrastructure as code support

### Information on docker image
- docker image: https://hub.docker.com/repository/docker/shadwell/docker-cobbler-supervisord
- is an official docker image available for this project?: No

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [x] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

### CODE REVIEW

**Comment by phillxnet** [comment]
@holmesb First off, thanks for the submission. I'm afraid I don't have time to review myself for a little while but hopefully someone can take a look. And if not I'll definitely have a go once our new release is out the door.

Just a quick note on the docker image choice. Given this is not an official docker image for the project, are there any alternatives that are also AArch64 as we are trying, going forward, to favour docker images that are both x86_64 (amd64) and aarch64. Just a thought.

**Comment by holmesb** [comment]
Hi @phillxnet I created this docker image.  No other images exist that have symlinks to a single data directory that Rockstor needs.  No official Cobbler docker image exists.
Its base-image is ubuntu:bionic and the Dockerfile is [here.](https://github.com/holmesb/docker-cobbler/blob/master/cobbler/Dockerfile)  I'm not sure where to start adding compatibility with AArch64.  I guess I would need a device of that architecture and get all the dependencies working.  In short, I doubt I'll ever get round to it.

It would be good for Rockstor to have more rockons beyond home-user\media stuff.  If its appeal is broadened among pro\business users, it's more likely to attract developers.  This PR fulfuls [demand ](https://forum.rockstor.com/t/pxe-tftp-server-for-network-boot/2449)in the forum.  Cobbler is still the best installation server IMO.  Others are either expensive, based on Ruby or over-scoped.  Cobbler is open-source, based on Python and focussed on Linux.  Rockstor's rivals (eg FreeNAS, unraid) lack any pxe-boot\installation server add-ons, so will give a competitive advantage.  I'm happy to help answer any questions the reviewer has and deal with any teething support problems.

**Comment by phillxnet** [comment]
@holmesb Super well put and I wholly agree, just wanted to see if such a thing was possible given our more recent push to adopting arm64 compatibility where we can, and our not yet having updated our pr template with this preference. And the increasing occurrence of arm64 available docker images. See @mcbridematt recent issue concerning this in the Rock-on context.

"[arm64] Discourage or prevent installation of Rockons that are not available on the machines architecture" #2191

x86_64 only is definitely not a blocker and I'm rather hoping that we have some interested parties help where they can on at least advising how such docker images might be dual targeted, or seeking out alternatives that are already arm64 compatible. But as you say it's all time and something is better than nothing, plus our current user-base is exclusively x86_64, but I'm keen to expand into the aarch64 options as we move to the Rockstor 4 re-launch.

Thanks again for preparing this Rock-on and addressing my query so fully. Maybe in time you will get aarm64 related pull requests on your indicated docker file, always the hope. But definitely not a blocker as stated.

**Comment by FroggyFlox** [comment]
Hi @holmesb , thanks a lot for this one!
I've been curious about this for a little while so that might as well be the perfect opportunity for me to give this a try! I might try to find some time in the coming days to give this a test ;)

In the meantime, would you have some pointers or examples of a quick functional test/demonstration? They seem to have a rather extensive documentation so I should be able to play with it thanks to that, but feel free to guide me in the right direction if you'd like.

@phillxnet , @holmesb , regarding the aarch64 option, I've never tried it myself (yet), but I believe the `buildx` docker tool should be the way to go... linking here for reference for whomever might want to try that one first (I probably will as soon as I can, but that won't likely be in the very near future, unfortunately).
https://github.com/docker/buildx

**Comment by mcbridematt** [comment]
@holmesb Something like this might help you do multiarch images:

https://github.com/ilteoood/docker_buildx

This is a GitHub action but you could probably copy the scripts inside into your own build mechanism.

You don't need a native ARM64 host - you can use qemu binary emulation which is what the tool above does.

**Comment by phillxnet** [comment]
@holmesb Any progress on the suggestions here regarding adding arm64 compatibility to your docker image?
@FroggyFlox & @mcbridematt have made suggestions in this pull request on that front.

Doing one of our repo tidy-ups.

**Comment by phillxnet** [comment]
Closing for now as repo tidy-up, please re-open upon further interest.

**Pull request closed without merging**
