### PR TITLE
Deluge Json is added.

### PR DESCRIPTION
**Pull request by tronder88**
Some think Deluge is better than transmission as torrent downloader. 
Also very easy to use

### CODE REVIEW

**Comment by schakrava** [comment]
Thanks @tronder88 . The app itself works great, but I cannot merge this pull request in it's current form because your branch is not up to date with master. Could you rebase with upstream's master? you should get updated README.md, couchpotato.json and sonarr.json.

For any new pull request, make sure to rebase your master branch first, and create a new branch with a unique name and open pr with that branch.

**Comment by tronder88** [comment]
Utorrent added as well, works brilliantly with Sonarr and Couchpotato. It has the --NET host config. Since some like to use utorrent with proxies, so this is done to have flexibility for portmapping

**Comment by schakrava** [comment]
This is great @tronder88. I'll make necessary changes and merge your request. But in future, please remember to submit one rock-on per pull request. Keeps things orderly.

**Comment by tronder88** [comment]
I am totally new to github. Started to use it 2 weeks ago for serious work. So I am sorry if there is some issues with my pull requests. Im not quite sure how I can create new pull requests with new rock-ons.

**Comment by schakrava** [comment]
no worries, really appreciate your contributions. The process is easy and similar to what we use for rockstor-core and rockstor-doc repositories as documented [here](http://rockstor.com/docs/contribute_documentation.html). I plan to create one for this repo in the README soon.

**Comment by schakrava** [comment]
@tronder88 I have manually merged your deluge.json with some corrections. It works great, thanks!

For utorrent, do we need PUID/PGID sections? Also the opts section does not look right. I'll close this pr without merging utorrent. Please submit a new pr for it. I have also updated the README with clear instructions on how to create a pr. Hope they will help you.

**Pull request closed without merging**
