### PR TITLE
Create radarr.json

### PR DESCRIPTION
**Pull request by alazare619**
Tested, Working, Wrapper for LinuxServer.io - Radarr.

Radarr is a fork of Sonarr with a focus on movies.

### CODE REVIEW

**Comment by alazare619** [comment]
@schakrava any update?

**Comment by Fredrik81** [comment]
The extra options added in the json file is not needed. this is for sonarr only.
Ref: https://hub.docker.com/r/linuxserver/radarr/

Options for docker:
-p 7878 - the port(s)
-v /config - Radarr Application Data
-v /downloads - Downloads Folder
-v /movies - Movie Share
-e PGID for for GroupID - see below for explanation
-e PUID for for UserID - see below for explanation
-e TZ for timezone information, eg Europe/London <--- not needed. If left out it will use the systems timezone

**Comment by alazare619** [comment]
Good catch I'll adjust the PR for this.

**Comment by alazare619** [comment]
@magicalyak can you audit this.

**Comment by alazare619** [comment]
@magicalyak  Removed the OPTS section.

**Comment by magicalyak** [comment]
Just need @schakrava to merge at this point.

**Comment by coleberhorst** [comment]
can confirm this radarr.json works on my system (latest stable rockstor)

**Comment by schakrava** [comment]
Thanks everyone for your contributions!

**Pull request merged**
