### PR TITLE
Add new Netdata (official) rock-on

### LINKED ISSUE #236: Netdata causing undesired AppArmor behavior
Upon installing Rockstor 4.0.1.0, enabling and configuring Rock-On service and installing the Netdata rockon the following appears cyclically on the console and in dmesg:

```
[404887.813445] audit: backlog limit exceeded
[404887.813505] audit: audit_backlog=65 > audit_backlog_limit=64
[404887.815997] audit: type=1400 audit(1599054448.661:817848324): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=22193 comm="apps.plugin" requested_mask="read" denied_mask
="read" peer="unconfined"
[404887.817281] audit: audit_lost=12218207 audit_rate_limit=0 audit_backlog_limit=64
```

The rate is about one cycle od messages per second 

The installation of Rockstor was performed by an image (OpenSUSE 15.2) created by kiwi-ng.
Upon check AppArmor and auditd are either disabled (apparmor) or not present at all (auditd) on the system.

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #236.

### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: Netdata
- website: https://www.netdata.cloud/
- description: Netdata is a scalable, distributed, real-time, performance and health monitoring solution for Linux, FreeBSD and MacOS. Out of the box, it collects 1k to 5k metrics per server per second. It is the corresponding of running top, vmstat, iostat, iotop, sar, systemd-cgtop and a dozen more console tools in parallel. Netdata is very efficient in this: the daemon needs just 1% to 3% cpu of a single core.

### Information on docker image
- docker image: https://hub.docker.com/r/netdata/netdata
- is an official docker image available for this project?: Yes, this PR uses it.

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [x] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

### CODE REVIEW

**Comment by FroggyFlox** [comment]
@Hooverdan96 ,

After a too much delay, I've finally made the changes we needed. I would appreciate if you could have a look at it on your side; it is the same rock-on as was previously in #237, but it cannot hurt to triple check the changes.

No worries if you don't have the time, and I'll merge it in. Thanks in advance!

**Comment by Hooverdan96** [comment]
I'll look at it tomorrow if that works.

**Review by Hooverdan96 — APPROVED** [review]
@FroggyFlox this looks good. I did another test install as well (for fun on my Tumbleweed Rockstor) and went all without a hitch. From my perspective: go for it!

**Comment by FroggyFlox** [comment]
Thanks a lot, @Hooverdan96 !

I re-tested it myself and confirm it works as intended on both x86_64 and Aarch64 machines so I'm going to merge it now.

**Comment by phillxnet** [comment]
@FroggyFlox Am I right in thinking that this Rock-on pr merge (Netdata (official)) was awaiting the review/merge/publication of:

"Add write-up for the Netdata_official rock-on ..." https://github.com/rockstor/rockstor-doc/pull/266

If so then let me know if you want me to deal with publication. Otherwise I'm happy for your to proceed as usual with the publication step.

**Comment by FroggyFlox** [comment]
@phillxnet, yes and no... I actually was waiting for a few other rock-ons that I wanted to merge before publishing but I seem to have dropped the ball on that one and got distracted by real-life obligations and then rockstor-core issues... I think we should get that published now as it has now been a while :-(

You can take care of it if that's not a problem on your end... let me know otherwise.

Sorry again for that.

**Pull request merged**
