### PR TITLE
Add YouTrack Official rock-on

### LINKED ISSUE #201: [Rock-on Update] YouTrack rock-on is out-of-date and not based on official image
The current image used by the [YouTrack](https://www.jetbrains.com/youtrack/) rock-on is using a non-official image hardcoded to use the 2018.2.42133 version. As of today, it also has been updated a year ago.

Notably, an [official image supported by JetBrains](https://hub.docker.com/r/jetbrains/youtrack) is available:
- updated 3 days ago
- uses 2019.2.58831 version

It would thus seem preferable to replace the current rock-on with a new one based on the official image.

### PR DESCRIPTION
**Pull request by FroggyFlox**
Fixes #201.

### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: YouTrack
- website: https://www.jetbrains.com/youtrack
- description: Issue tracker designed for development teams. 

### Information on docker image
- docker image: https://hub.docker.com/r/jetbrains/youtrack
- is an official docker image available for this project?: yes. Note that the version needs to be hardcoded using the image tag. This PR uses the latest available: 2019.2.58831.

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [x] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

@phillxnet, as this rock-on needs specific pre-install setup related to ownership of shares, I was thinking of documenting these first a write-up in Rockstor documentation to provide step-by-step instructions (see https://github.com/rockstor/rockstor-doc/issues/211) and linking to it in this rock-on's description. As a result, this PR would be dependent on https://github.com/rockstor/rockstor-doc/issues/211, which explains why I'm leaving it in "_Draft_" state for now. Thanks for letting me know what you think of the idea.

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox If I am following you correctly this pr is now no longer 'in progress', so if you could change it's draft status I can merger and sync release with your related pending doc pull request.

**Comment by phillxnet** [comment]
@FroggyFlox and in case you were wanting to match up more exactly the target within the docs once you doc pull request has been merged, from my initial tests of a local build here it should end up being:
```
rockstor.com/docs/docker-based-rock-ons/youtrack.html
```

**Comment by FroggyFlox** [comment]
Hi @phillxnet,

I was actually actually waiting for the associated doc write-up to be released as I wanted to link to it from the `"description"` of this rock-on. This was mostly related to the pre-install requirements on user creation and shares ownership. In its current state, it is linking to the rock-ons section of the documentation, but not precisely to the YouTrack write-up.
I realize now I can "predict" what the exact link will be however, so I can make that change without waiting for the doc write-up to be published.

I may not have access to my setup for the next few hours, however...

Sorry for the confusion...

**Comment by FroggyFlox** [comment]
@phillxnet, it should be all good to go now.

Thanks for pointing to me this much better solution!

**Comment by phillxnet** [comment]
@FroggyFlox Super, that was quick. Link confirms as good in draft publish of docs so I'll merge here and test then publish if all looks good.

**Comment by phillxnet** [comment]
@FroggyFlox Strange thing. Nothing published yet though. That last link as submitted is not yet showing up when patching GitHub in place of production. So will hold off for a bit to confirm mutual function then publish. I'm actually almost done on an alternative testing method so will continue with that as should be quicker and more reliable anyway.

**Comment by phillxnet** [comment]
@FroggyFlox I see it now. It looks like you have changed only one of the links. Which leave the existing one in description marked as "Important" as unchanged. I'll get on with completing my more robust test setup and if you fancy popping in another quick pr with a patch to the second link then great and I can then pop that in prior to publishing. Nothing published yet so no worries and apologies for me not catching that change. Should be easier to do end to end testing very shortly.

**Comment by FroggyFlox** [comment]
> @FroggyFlox I see it now. It looks like you have changed only one of the links. Which leave the existing one in description marked as "Important" as unchanged. I'll get on with completing my more robust test setup and if you fancy popping in another quick pr with a patch to the second link then great and I can then pop that in prior to publishing. Nothing published yet so no worries and apologies for me not catching that change. Should be easier to do end to end testing very shortly.

You're absolutely correct.... I was too quick to make the edits and missed the first (and most important) link. I'll submit a PR right away correcting this.

**Comment by phillxnet** [comment]
@FroggyFlox This is now published, along with it's associated url patch.

Thanks again for this and I now have my 'new improved' rock-ons test system in place so should be smoother going forward: or at least that's the hope.

**Comment by FroggyFlox** [comment]
Thanks a lot for all of that, @phillxnet!

**Pull request merged**
