### PR TITLE
use new official jenkins image. Fixes #177

### LINKED ISSUE #177: use new official jenkins image
Our current Jenkins Rock-on uses the now deprecated jenkins image.

As per quote from: https://hub.docker.com/_/jenkins (last updated 7 months ago).
"This image has been deprecated in favor of the jenkins/jenkins:lts image provided and maintained by Jenkins Community as part of project's release process. The images found here will receive no further updates after LTS 2.60.x. Please adjust your usage accordingly."

Last version as of writing 2.60.3 (2017-08-17) see below LTS changelog.

LTS variant's changelog: https://jenkins.io/changelog-stable/

See the following link for the proposed new image:
https://hub.docker.com/r/jenkins/jenkins (last updated hours ago)
Latest LTS version noted as 2.150.2 (2019-01-16) 19 LTS releases on from 2.60.3

Note that various versions (tags) of this image are available, most notably.

jenkins/jenkins:lts Proposed for our Rock-on edit.
jenkins/jenkins Defaults to the 'latest' (tag) weekly.

Multiple other tags are available:
https://hub.docker.com/r/jenkins/jenkins/tags

It is proposed that we adopt the 'lts' tag for our existing Rock-on update as this is in line with it's current image.

### PR DESCRIPTION
**Pull request by phillxnet**
Text and image update of existing Jenkins CI Rockon. See issue #177 for context.

Summary of changes
- update image
- spaces not tabs
- Improve description, adding docker image reference

Fixes #177 

Ready for review.

Caveat:
This Rock-on's user facing text states/assumes its use of the LTS variant docker image. However we have an outstanding rockstor-core issue (with pending pr fix) that this Rockon depends upon.

Prior to review dependencies:

Issue:
"honour tag element within rock-on json #2014"
https://github.com/rockstor/rockstor-core/issues/2014

Pull request currently pending:
"honour tag element within rock-on json. Fixes #2014"
https://github.com/rockstor/rockstor-core/pull/2016

### CODE REVIEW

**Comment by phillxnet** [comment]
Not adding 'needs review' label just yet due to currently unmet dependencies within rockstor-core.

**Comment by phillxnet** [comment]
Adding 'needs review' as we now have the prior indicated rockstor-core pr dependency merged:

> Pull request currently pending:
> "honour tag element within rock-on json. Fixes #2014"
> [rockstor/rockstor-core#2016](https://github.com/rockstor/rockstor-core/pull/2016)

**Comment by phillxnet** [comment]
Please note that this Rock-on pr requires at least Rockstor version 3.9.2-49 (as yet unreleased) to review, or at least master branch at time of writing this comment.

**Comment by phillxnet** [comment]
This Rock-on can now be reviewed as per:

> ...this Rock-on pr requires at least Rockstor version 3.9.2-49 (as yet unreleased)

As we now have 3.9.2-49 (and 50) out.

**Comment by phillxnet** [comment]
I'm reluctant to leave this much longer as Jenkins servers are often very privileged re credentials and our currently published Rock-on docker image is now very old. So merging 'as is' for now.
Their is the caveat that unless run with at least Rockstor version 3.9.2-49 it will not pull LTS as advertised but Latest. Given this Rock-on is likely professionally / expertly used I'm assuming the same user will have ensured Rockstor is fully updated. And if not they should recognise they are not running their chosen version and any bug report can be directed towards the indicated, now merged and published, pull request.
@FroggyFlox Apologies if I've jumped the gun on this one but eager to deal with or current backlog of old / broken Rock-ons.

**Comment by FroggyFlox** [comment]
Thanks for doing this, @phillxnet... I apologize for not having a look at that one since 3.9.2-49 was out.

**Comment by phillxnet** [comment]
@FroggyFlox No worries, I'd tested pretty thoroughly way back and have just given it another install, reboot pre publishing and all looks to be OK.
It's now published so that's a relief as our last one was unreasonably old now which is especially sensitive for apps such as this.
Also the warning in info section re Firefox bug is now redundant but no harm for now. Also interesting in that it runs using the share ownership and states this in the user facing text which I like.

**Pull request merged**
