### PR TITLE
Removing SymForm as the service was closed down. 

### PR DESCRIPTION
**Pull request by jmhardison**
Symform service was closed down. Client does not operate without service. Removing this Rockon. This is in regards to issue #56

### CODE REVIEW

**Comment by phillxnet** [comment]
@jmhardison Great thanks.
Do you fancy also adding another commit to this pull request to remove the Symform entry from the root.json index file:

https://github.com/rockstor/rockon-registry/blob/master/root.json#L41

That would round our the change and make for a more complete removal. No worries otherwise and thanks for your contribution in getting this one sorted.

**Comment by jmhardison** [comment]
absolutely can. Sorry I saw that file but didn't see any other request modifying it. So meh. :) I'll get that added in a sec.

**Comment by jmhardison** [comment]
And done. thanks.

**Comment by phillxnet** [comment]
@jmhardison Super thanks.

Yes @schakrava (project lead and master merger) normally takes care of keeping that file in sync on an 'on the fly' nature, but slightly neater if it's modification is included in this pull request.

Cheers.

**Comment by schakrava** [comment]
Thank you @jmhardison @magicalyak @phillxnet

**Pull request merged**
