### PR TITLE
Logitechmediaserver

### PR DESCRIPTION
**Pull request by jfearon**
Remove the old version of logitech squeezebox server and replace with docker image for logitech media server.  This means that:

1) Logitechs rename is reflected in the rock on name
2) by switching docker image the latest version of the media server is pulled in

### CODE REVIEW

**Comment by jfearon** [comment]
Not sure about the filename change - if that causes massive problems it can be changed!

**Comment by Brookke** [comment]
@jfearon looks like you need to also update the root.json file 😊

**Comment by phillxnet** [comment]
@jfearon Thanks for your earlier efforts on this. I'm doing some tidy up and this looks to be in limbo. Would be nice to have it reach a conclusion of sorts.
I appreciate that much time has passed but if this is still of interest then @FroggyFlox last comment might be a good place to start.

**Comment by phillxnet** [comment]
Closing as resolved in #300 and #283 respectively.

**Pull request closed without merging**
