### PR TITLE
add cardigann rock-on

### PR DESCRIPTION
**Pull request by absentbri**
Cardigann is like Jackett but maintained differently, and more open to non-private trackers.

### CODE REVIEW

**Comment by phillxnet** [comment]
@absentbri Thanks for presenting this Rock-on, much appreciated and sorry to the significant delay. Please indicate if you still consider this pull request ready to merge.

Requesting a review of this pr and labelling accordingly.

**Comment by absentbri** [comment]
As far as I know this is still good to go. I moved to UnRaid about a year ago so I've no way of confirming. This was in 2017...

**Comment by phillxnet** [comment]
@absentbri Thanks for the confirmation, and again apologies for the 'poor show' re repo maintenance.
Just trying to sort our entire backlog so the same unreasonable delays are at least less likely to happen.

Requesting a review of this Rock-on by anyone interested.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for yet another review.
I'll look to merging this pr shortly on the strength of this and adding it's required root.json entry.

**Pull request merged**
