### PR TITLE
http->https redirector for web ui

### PR DESCRIPTION
**Pull request by nfriedly**
Solves this issue: https://forum.rockstor.com/t/automatic-http-https-redirection/2052

Tested by installing it locally and suddenly http://rockstor.local/ works :)

### CODE REVIEW

**Comment by magicalyak** [comment]
I really like this idea, as I prefer the redirect also and this gives you the option.  Ideally perhaps we will have a feature toggle in the options, but until then, this is a great concept.  Do we already have the MIT license in Rockstor?  If so we are fine (not sure why the maintainer used the MIT license).  The repo looks good, it's alpine running the reflector.  Can we change the repo to geldim/https-redirect (it has +1M pulls) and no worries on the license.  I tested the same json with that repo and it worked great.

**Comment by nfriedly** [comment]
Switched ;)

**Comment by magicalyak** [comment]
Just need to wait on @schakrava to merge at this point, looks good to me!

**Comment by schakrava** [comment]
We'll add this as a feature in rockstor-core, but happy to merge this in the meantime. Thanks @nfriedly and @magicalyak

**Pull request merged**
