### PR TITLE
Add qbittorrent + openvpn rock-on

### PR DESCRIPTION
**Pull request by Marenz**
The existing torrent client transmission + openvpn unfortunately misses
a feature I very much like: sequential downloading.

Thus I added qbittorrent + openvpn.

This rock-on can also be used without openvpn if you simply select eth0
as the interface in the qbittorrent webui and don't provide a
configuration (not tested that scenario though).

### General information on project
This pull request proposes to add a new rock-on for the following project:
- name: qbittorrent + openvpn
- website: www.qbittorrent.org/
- description: A bittorrent client with the feature of sequential downloading.

### Information on docker image
- docker image: https://hub.docker.com/repository/docker/marenz/qbittorrent-openvpn based on https://hub.docker.com/r/linuxserver/qbittorrent
- is an official docker image available for this project?: No

### Checklist
- [x] Passes [JSONlint](https://jsonlint.com) validation
- [x] Entry added to `root.json` in _alphabetical_ order (for new rock-on only)
- [x] `"description"` object lists and links to the docker image used
- [x] `"description"` object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] `"website"` object links to project's main website

### CODE REVIEW

**Comment by Superfish1000** [comment]
Everything seems to be working so far.  I haven't checked the OpenVPN connection though.
I'd recommend that you mention adding the openVPN.conf in the description.  I wasn't sure for a moment.  I'm also not clear what was required for the local net mask.  I'm assuming it meant the net mask of the local network, ie 255.255.255.0
I'd clarify those and then it should be good.

**Comment by kageurufu** [comment]
I would prefer a solo qBittorrent container, and having it connect through the already existing OpenVPN rockon.

**Comment by phillxnet** [comment]
> I would prefer a solo qBittorrent container, and having it connect through the already existing OpenVPN rockon.

@kageurufu Nice idea and our recently added rock-nets may make this relatively accessible/easy to achieve. But note that our existing OpenVPN rock-on is super clunky in my mind at least. The ease of install/setup idea of Rock-ons does conflict a little with single server single docker image arrangement so a few of our Rock-ons have adopted some 'heavy weight' images that are all inclusive.

The rock-nets facility added by @FroggyFlox in 4.0.5 is a major step towards being able to host more idealised/advanced arrangements via:
"Implement docker networks. ...": https://github.com/rockstor/rockstor-core/pull/2207
release: https://github.com/rockstor/rockstor-core/releases/tag/4.0.5-0
See:
Docker network (Rocknet): https://rockstor.com/docs/interface/system/network.html#docker-network-rocknet
and the in-turn linked:
Joining Rocknets: https://rockstor.com/docs/interface/overview.html#joining-rocknets

But this necessarily adds a level of setup complexity. Hopefully still relatively accessible thought. I see us offering all-in-one as well as more idealised single server rock-ons for those wishing to do the inter server knitting themselves.

@Marenz Appologies for this pull requests apparent abandonment. It looks like we have yet to receive a full functional review. I.e.:

> I haven't checked the OpenVPN connection though.

But hopefully this can be resolved soon.

@Superfish1000 Thanks for the initial review on this one, and some good suggestions. Any chance you could test the openvpn bit. That way we could get this one moving again. Cheers.

**Comment by phillxnet** [comment]
@Marenz 
Closing as doing a repo tidy-up plus no response to re-base request, plus your custom docker image was last updated 2 years ago now. No worries if you are still interested in getting this Rock-on in. Just re-open and rebase so we can test. Also note we now have an expectation for multi-arch compatibility. I.e. amd64 & arm64.  Along with a note in the description indicating this.

**Pull request closed without merging**
