### PR TITLE
Adding FreshRSS

### PR DESCRIPTION
**Pull request by nfriedly**
Took a couple of tries to install, but I think that's because of an issue specific to my server (every rock-on seems to take a few tries to install right now...)

Worked smoothly with a SQLite DB after that.

### CODE REVIEW

**Comment by magicalyak** [comment]
Since this takes a name, can you make an environment variable to customize that?  You can look at one of mine for a messy version of some example if you like https://github.com/rockstor/rockon-registry/pull/84/files  (I'm not trying to show off, that JSON isn't the best but it has a lot of environment variables, so it's a good template).

**Comment by magicalyak** [comment]
Also for styling, can you move the description and those fields to the bottom (look at existing rockons for reference).

**Comment by nfriedly** [comment]
Are you referring to the `--name` parameter? I might be misunderstanding something, but I think that's a docker thing that applies to all containers and is really just for convenience when working with it from the command line (?)

As for the description, I suppose we can move it, although I personally think that having the website and 1-line description at the top is preferable.

**Comment by magicalyak** [comment]
No clue why I thought that! You're completely right! Ok ignore that comment then.  
The styling is just what we started with and have been enforcing (to some extent).  If you could just move that to the bottom I'll approve and then hopefully suman will merge soon.  I haven't seen any rockons go through without those items towards the bottom.  If this were the first rock-on, I'd totally agree with you though.

**Comment by nfriedly** [comment]
Hum.. What if I send another PR that moves the description and URL to the top of *all* the .json files here?

**Comment by magicalyak** [comment]
I think you'll be waiting a long time to get it merged.  I'd move to bottom and then create an issue for feedback.  It's certainly possible but from my experience, the odds of the PR being merged quickly may not be so great.  Just trying to get this one in before the next review for PRs.

**Comment by magicalyak** [comment]
@phillxnet how big of a deal is this?  personally I don't care but I haven't seen the descriptions on top in the other rock-ons?

**Comment by nfriedly** [comment]
OK, it's moved for this PR. I bet we could put together a script that enforces some of the rules and can automatically fix things like this.

**Comment by nfriedly** [comment]
Although, I suspect that at some point you'll have to move beyond a git repo wit a bunch of files for the registry...

**Comment by magicalyak** [comment]
Another (add , on line 36)
Error while processing Rock-on profile at /opt/rockstor/rockons-metastore/FreshRSS.json. Lower level exception: Expecting , delimiter: line 36 column 3 (char 899)

**Comment by phillxnet** [comment]
@magicalyak re the ordering of elements I don't think it's a big deal really but a nice to have, given most of our rock-ons currently follow this ordering. Nice to keep them all looking roughly the same.

Also I find the following web page helpful in checking for basic json compliance:

http://jsonlint.com/

**Comment by magicalyak** [comment]
@nfriedly I'm good with original version then if you like or the fixed with changes above, just let me know in your next commit and I'll review/approve.

**Comment by nfriedly** [comment]
Doh, sorry. Would you be interested in a travis-ci script that automatically tests merges and PR's for, e.g. valid JSON?

**Comment by phillxnet** [comment]
@nfriedly good idea re JSON validation checks. Our other 2 main repositories (core and docs) have Jenkins integration (running as a rock-on I believe) but it's not yet connected to this repo for anything. That's definitely one for @schakrava .

**Comment by magicalyak** [comment]
You just did what I was about to write!
This Rock-On is great, works and approved by me. We just need to wait for @schakrava to merge.

**Comment by schakrava** [comment]
LGTM, works smoothly! Thank you @nfriedly. Thanks for your thorough review @magicalyak . I second @phillxnet's comment that we don't nitpick on style that much.

**Comment by schakrava** [comment]
@nfriedly feel free to open a pr with CI changes. We use jenkins as @phillxnet mentioned, and I'd be interested in automating some checks for sure.

**Pull request merged**
