### PR TITLE
Create sabnzbd.json

### PR DESCRIPTION
**Pull request by dizzi90**
Modified BTSync.json to  add sabnzbd support.

### CODE REVIEW

**Comment by schakrava** [comment]
Could you please confirm that this works? timhaak/docker-sabnzbd image does not exist. Please look at the instructions [here](https://github.com/rockstor/rockon-registry/blob/master/README.md) on how to test by adding to local metastore.

**Comment by HBDK** [comment]
I think he might have used the name of the github repo and not the docker i have pasted the changes i had to make to get it working.
`

    "Sabnzbd+": {
        "containers": {
            "sabnzbd": {
                "image": "timhaak/sabnzbd",
                "launch_order": 1,
                "ports": {
                    "8080": {
                        "description": "Port for Sabnzbd Web interface. Suggested default: 8080.",
                        "host_default": 8080,
                        "label": "WebUI port",
                        "procotol": "tcp"
                    }
                },
                "volumes": {
                    "/data": {
                        "description": "Choose a share to download to.",
                        "label": "Data Storage"
                    },
                    "/config": {
                        "description": "Choose a share to host configuration.",
                        "label": "Config Storage"
                    }
                }
            }
        },
        "description": "Sabnzbd+",
        "more_info": "",
        "ui": {
            "slug": ""
        },
        "volume_add_support": true,
        "website": "https://www.sabnzbd.org/",
        "version": "alpha"
    }
}

`

**Comment by schakrava** [comment]
Thanks for your input @HBDK. I just merged another pull request for sabnzbd. It uses image from linuxserver.io. Are you the maintainer of the image in this pull request? Are there any advantages to using this image over linuserver/sabnzb?

**Comment by HBDK** [comment]
no i don't maintain any images. i was just trying to make the bare essentials run before i revived the hardware for my next server.. ;) 
but Linux.io looks like i might be a better choice.

**Comment by schakrava** [comment]
Cool. I am closing this pr.

**Pull request closed without merging**
