### PR TITLE
Rockon for the new V4/Dev branch of Ombi.

### PR DESCRIPTION
**Pull request by Superfish1000**
Fixes # NA.

General information on project
This pull request proposes to add a new rock-on for the following project:

name: Ombi V4/Dev branch
website: https://ombi.io/
description: The only change from the current Ombi Rockon is the Docker tag and the description.
Information on docker image
docker image: https://hub.docker.com/r/linuxserver/ombi/
is an official docker image available for this project?: Yes.
Checklist
- [x] Passes JSONlint validation
- [x] Entry added to root.json in alphabetical order (for new rock-on only)
- [x] "description" object lists and links to the docker image used
- [x] "description" object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
- [x] "website" object links to project's main website

Note: Previous pull request had an invalid character in the docker container name field.  This caused an error on import.  I have corrected it.

### CODE REVIEW

**Comment by Superfish1000** [comment]
Added a Rockon for Tautulli to replace the PlexPy Rockon that is now deprecated.

Fixes # Deprecated PlexPy Rockon.

General information on project
This pull request proposes to add a new rock-on for the following project:

name: Tautulli
website: https://tautulli.com/
description: The only change from the current PlexPy Rockon is using the official Tautulli Docker repo and the relevant names in the descriptions.
Information on docker image
docker image: https://hub.docker.com/r/tautulli/tautulli
is an official docker image available for this project?: Yes.
Checklist
[ * ] Passes JSONlint validation
[ * ] Entry added to root.json in alphabetical order (for new rock-on only)
[ ] "description" object lists and links to the docker image used
[ * ] "description" object provides information on the image's particularities (advantage over another existing rock-on for the same project, for instance)
[ * ] "website" object links to project's main website

**Comment by phillxnet** [comment]
@Superfish1000 I suspect you have mixed your branches up here. Your original:
Rockon for the new V4/Dev branch of Ombi. #269
is submitted using the Superfish1000:master
and you appear to have added an additional commit to this branch that is unrelated and includes another proposed addition.

In order for each submission to be assessed individually you need to have dedicated git branches for each. That way they are divided and can be addressed in isolation.

Easiest way is to create specific branches for each proposed submission, pull request, and not work directly in the master branch.

As a hint. If you are less familiar with git / GitHub you can simply close your existing pull requests and create 2 new ones each from fresh branches named according to the rock-on in question say.

Hope that helps.

**Comment by Superfish1000** [comment]
> @Superfish1000 I suspect you have mixed your branches up here. Your original:
> Rockon for the new V4/Dev branch of Ombi. #269
> is submitted using the Superfish1000:master
> and you appear to have added an additional commit to this branch that is unrelated and includes another proposed addition.
> 
> In order for each submission to be assessed individually you need to have dedicated git branches for each. That way they are divided and can be addressed in isolation.
> 
> Easiest way is to create specific branches for each proposed submission, pull request, and not work directly in the master branch.
> 
> As a hint. If you are less familiar with git / GitHub you can simply close your existing pull requests and create 2 new ones each from fresh branches named according to the rock-on in question say.
> 
> Hope that helps.
You're 100% correct.  My apologies.  I am not used to using github; especially for pull requests.  Please ignore the spastic mess of commits since my last comment.  The branch is back to it's previous state.  I'll submit the Tautulli Rockon again in it's own branch.

**Comment by phillxnet** [comment]
@Superfish1000 Thanks for sorting the branch mix-up out and for the recent tweaks to this pr. Hopefully we will get a review of this pr's current state shortly.

**Comment by Superfish1000** [comment]
@FroggyFlox If you get a chance could you take a look at this one too.  The currently live Ombi Rockon is deprecated and no longer supported.  While this branch is technically still in development it is now the mainline branch according to the devs.

**Comment by FroggyFlox** [comment]
Thanks for the information, @Superfish1000.

I am indeed reticent in using a development branch as we usually prefer a "stable" branch, but if this is what the Ombi developers recommend, then that changes things. I'll try to have a look at it next!

**Comment by FroggyFlox** [comment]
Hi @Superfish1000 ,

Sorry again for being so slow on this one; life keeps getting in the way lately and the little time I had to work on Rockstor was spent on urgent changes required on our back-end.

I just had another look and it seems I was so slow on this one that the Ombi project made v4 their main release. Upon installing our current Rock-On I had:
```
May 30 14:25:38 rockdev linuxserver/ombi:latest/ombi[14704]: Hello, welcome to Ombi
May 30 14:25:38 rockdev linuxserver/ombi:latest/ombi[14704]: Valid options are:
May 30 14:25:38 rockdev linuxserver/ombi:latest/ombi[14704]: Ombi 4.0.1342
May 30 14:25:38 rockdev linuxserver/ombi:latest/ombi[14704]: Copyright (C) 2021 Ombi
```
It thus pulls and uses v4.0.1342.

Although the main reason for this pull-request is thus no longer a problem, I do like the improvements you made to the `"description"` field so feel free to open a new issue to include them for our current Rock-On.

Sorry again for dropping the ball on this one, and let us know if you're game with creating the issue I mentioned above. I promise this time will be quick as it would only involve "cosmetic" changes.

**Comment by Superfish1000** [comment]
Life happens whether you're ready for it or not.  It's no trouble.  I haven't looked at it since the original pull.  I'll look into creating an update.

**Comment by Hooverdan96** [comment]
@phillxnet, @FroggyFlox, @Superfish1000, since the current Rockon pulls the latest Ombi dev branch, should this pull request be closed?

**Comment by phillxnet** [comment]
> @phillxnet, @FroggyFlox, @Superfish1000, since the current Rockon pulls the latest Ombi dev branch, should this pull request be closed?

Yes I think so, thanks for looking into this one.

@Superfish1000 My apologies for my insufficient maintenance within this repo. If you do fancy resubmitting anything then just jump in with a new pr and that would be most welcome. We are now moving to a delete anything really old or known non working in an attempt to address our long standing backlog as it's way easier to just remove and re-add stuff than to have it awaiting attention and potentially discouraging folks.

Thanks again for the effort put into this pull request and again my apologies for not cleaning house properly and in a frequent and timely manner.

**Pull request closed without merging**
