### PR TITLE
added MariaDB rock-on

### PR DESCRIPTION
**Pull request by dschoorisse**
MariaDB database, based on <https://hub.docker.com/r/linuxserver/mariadb/>

### CODE REVIEW

**Comment by schakrava** [comment]
Thanks for the pull request @dschoorisse. A couple of comments

1. The container is named Sonarr, please name it as linuxserver-mariadb
2. It would be very helpful to add a "more_info" with information such as how to access the db from cli etc.. See openvpn.json for example.

**Comment by dschoorisse** [comment]
Oops, renamed it locally but forgot to check in. I will fix it. Thanks for you respons!

**Comment by dschoorisse** [comment]
Hi, this is fixed now :)

**Comment by schakrava** [comment]
I found an error in the naming of the database password env variable. Please see my changes. With the wrong env variable, root's password is not set, so you can login without password :)

Thanks for your work on this. I think this is a very useful Rock-on for advanced users wanting a mariadb/mysql database.

**Pull request merged**
